"""Local reference tables for the cooking guide: roasting times, safe core temperatures, substitutions, UK seasonal
produce, cup weights and drink pairings. Rough home-cooking guides; a probe thermometer has the final word.
"""

# Conventional oven °C, minutes per kg, extra minutes, resting minutes, core °C to aim for.
ROASTS = {
    "chicken": {"temp": 190, "per_kg": 40, "extra": 20, "rest": 15, "core": 75, "label": "chicken"},
    "beef rare": {"temp": 180, "per_kg": 40, "extra": 20, "rest": 20, "core": 52, "label": "beef, rare"},
    "beef medium": {"temp": 180, "per_kg": 50, "extra": 25, "rest": 20, "core": 60, "label": "beef, medium"},
    "beef well done": {"temp": 180, "per_kg": 60, "extra": 30, "rest": 20, "core": 71, "label": "beef, well done"},
    "lamb rare": {"temp": 180, "per_kg": 40, "extra": 20, "rest": 15, "core": 55, "label": "lamb, pink"},
    "lamb medium": {"temp": 180, "per_kg": 50, "extra": 25, "rest": 15, "core": 60, "label": "lamb, medium"},
    "lamb well done": {"temp": 180, "per_kg": 60, "extra": 30, "rest": 15, "core": 71, "label": "lamb, well done"},
    "pork": {"temp": 180, "per_kg": 60, "extra": 30, "rest": 15, "core": 71, "label": "pork"},
    "turkey": {"temp": 190, "per_kg": 20, "extra": 70, "rest": 45, "core": 75, "label": "turkey"},
}
TURKEY_BIG_KG = 4.5
TURKEY_BIG_EXTRA = 90

# (food, core °C, note) — UK Food Standards Agency advice is 70°C for 2 minutes (or 75°C for 30 seconds) for poultry,
# pork, mince, sausages and reheated food.
SAFE_TEMPS = [
    ("Chicken, turkey, duck (whole or pieces)", 75, "no pink meat, juices run clear"),
    ("Minced meat, burgers, sausages", 75, "no pink in the middle"),
    ("Pork (joints, chops)", 71, "or 70°C held for 2 minutes"),
    ("Stuffing (in or out of the bird)", 75, ""),
    ("Reheated leftovers", 75, "steaming hot all the way through, reheat once only"),
    ("Beef or lamb, rare (whole joints and steaks)", 52, "whole cuts only; the outside must be seared"),
    ("Beef or lamb, medium", 60, ""),
    ("Beef or lamb, well done", 71, ""),
    ("Fish", 63, "flesh flakes and turns opaque"),
    ("Egg dishes (quiche, frittata)", 71, "set in the middle"),
    ("Gammon and ham joints", 71, ""),
    ("Hot-holding cooked food", 63, "keep above this if it's sitting out"),
]

SUBSTITUTES = {
    "buttermilk": "250 ml milk plus 1 tbsp lemon juice or white vinegar, left 10 minutes; or thinned plain yoghurt",
    "egg": "1 tbsp ground flaxseed plus 3 tbsp water (rest 5 min); or 60 g mashed banana or apple sauce in cakes",
    "self-raising flour": "150 g plain flour plus 2 tsp baking powder",
    "baking powder": "1 tsp = ¼ tsp bicarbonate of soda plus ½ tsp cream of tartar",
    "bicarbonate of soda": "3 tsp baking powder per 1 tsp bicarb (and cut any salt)",
    "cake flour": "Plain flour with 2 tbsp per 125 g swapped for cornflour",
    "bread flour": "Plain flour; the dough will be a little softer",
    "cornflour": "2 tbsp plain flour per 1 tbsp cornflour for thickening; or arrowroot 1 to 1",
    "double cream": "Mascarpone loosened with milk; or 75 g melted butter plus 175 ml milk (not for whipping)",
    "single cream": "Half milk, half double cream; or evaporated milk",
    "soured cream": "Greek yoghurt; or crème fraîche",
    "crème fraîche": "Soured cream or Greek yoghurt (add yoghurt off the heat so it doesn't split)",
    "mascarpone": "Full-fat cream cheese beaten with a splash of cream",
    "ricotta": "Cottage cheese, blended smooth",
    "greek yoghurt": "Plain yoghurt strained through a sieve and kitchen paper for an hour",
    "milk": "Any plant milk 1 to 1; or half evaporated milk, half water",
    "butter": "Baking: 80 g oil per 100 g butter, or a baking spread 1 to 1; frying: oil",
    "margarine": "Butter 1 to 1",
    "vegetable oil": "Sunflower, rapeseed or light olive oil; melted butter in baking",
    "olive oil": "Rapeseed or sunflower oil",
    "caster sugar": "Granulated sugar blitzed for a few seconds",
    "icing sugar": "Caster sugar blitzed to a powder with 1 tsp cornflour per 100 g",
    "brown sugar": "White sugar plus 1 tbsp black treacle or molasses per 200 g",
    "golden syrup": "Honey or maple syrup 1 to 1",
    "honey": "Golden syrup, maple syrup or agave 1 to 1",
    "maple syrup": "Honey or golden syrup; add a drop of vanilla",
    "treacle": "Molasses 1 to 1; or dark brown sugar with a little water",
    "vanilla extract": "Vanilla paste 1 to 1; or the seeds of ½ pod per tsp; or maple syrup",
    "chocolate": "3 tbsp cocoa plus 1 tbsp butter or oil per 30 g dark chocolate",
    "cocoa powder": "30 g dark chocolate per 3 tbsp cocoa (cut the fat and sugar a little)",
    "breadcrumbs": "Crushed crackers, oats, cornflakes or panko",
    "panko": "Ordinary dried breadcrumbs, toasted",
    "yeast (dried)": "Fresh yeast at 3 times the weight; instant yeast at about ¾ of it",
    "gelatine": "Agar agar: about 1 tsp powder sets 250 ml (boil it briefly)",
    "wine (red)": "Stock with 1 tbsp red wine vinegar per 250 ml; or grape juice with a splash of vinegar",
    "wine (white)": "Stock with a squeeze of lemon; or white grape juice with a splash of vinegar",
    "beer": "Stock; or non-alcoholic beer",
    "stock cube": "1 tsp bouillon powder or a stock pot per 500 ml water",
    "chicken stock": "Vegetable stock 1 to 1",
    "lemon juice": "Lime juice 1 to 1; or half the amount of white wine vinegar",
    "lime juice": "Lemon juice 1 to 1",
    "white wine vinegar": "Cider vinegar or rice vinegar; lemon juice at a push",
    "balsamic vinegar": "Red wine vinegar plus a pinch of sugar",
    "rice vinegar": "Cider vinegar with a pinch of sugar",
    "soy sauce": "Tamari (gluten-free) or coconut aminos; Worcestershire sauce in small amounts",
    "worcestershire sauce": "Soy sauce with a dash of vinegar and sugar",
    "fish sauce": "Soy sauce plus a squeeze of lime",
    "tomato puree": "3 tbsp passata per 1 tbsp purée, cooked down; or ketchup at a push",
    "passata": "Tinned chopped tomatoes, blended and sieved",
    "fresh herbs": "Dried herbs at a third of the amount (add them earlier)",
    "garlic clove": "⅛ tsp garlic powder or ½ tsp garlic purée per clove",
    "onion": "1 tbsp dried onion flakes or 1 tsp onion powder per small onion; or leeks or shallots",
    "shallot": "A little red or white onion",
    "fresh ginger": "¼ tsp ground ginger per tbsp grated fresh; or ginger paste 1 to 1",
    "mustard powder": "1 tbsp prepared mustard per 1 tsp powder",
    "dijon mustard": "Wholegrain or English mustard (English is hotter, use less)",
    "mayonnaise": "Greek yoghurt; or half yoghurt, half mayo",
    "parmesan": "Pecorino or Grana Padano; for vegetarians a vegetarian hard cheese; nutritional yeast for vegans",
    "mozzarella": "Cheddar or any mild melting cheese",
    "pine nuts": "Sunflower or pumpkin seeds (nut-free), or chopped cashews",
    "ground almonds": "Plain flour for texture (less rich); ground sunflower seeds for nut-free",
    "coconut milk": "Single cream; or yoghurt added at the end off the heat",
    "sour cream": "Greek yoghurt; or crème fraîche",
    "cream of tartar": "Lemon juice: 1 tsp per ½ tsp cream of tartar when whisking egg whites",
    "rice": "Bulgur wheat, couscous, quinoa, or cauliflower rice",
    "pasta": "Gluten-free pasta; or courgetti",
    "cheddar": "Red Leicester, Double Gloucester or Gruyère",
}

# UK seasonal fruit and vegetables by month (roughly; outdoor British-grown).
SEASONAL = {
    1: ("brussels sprouts, cabbage, cauliflower, celeriac, kale, leeks, parsnips, swede, turnips, purple sprouting broccoli",
        "forced rhubarb, apples (stored), pears (stored), blood oranges and Seville oranges (imported)"),
    2: ("brussels sprouts, cabbage, cauliflower, celeriac, kale, leeks, parsnips, swede, purple sprouting broccoli",
        "forced rhubarb, apples (stored), blood oranges (imported)"),
    3: ("cauliflower, kale, leeks, purple sprouting broccoli, spring greens, spring onions, wild garlic",
        "forced rhubarb"),
    4: ("asparagus (late), purple sprouting broccoli, spring greens, spring onions, radishes, watercress, wild garlic",
        "rhubarb"),
    5: ("asparagus, new potatoes (Jersey Royals), radishes, rocket, spinach, spring onions, watercress, lettuce",
        "rhubarb, early strawberries"),
    6: ("asparagus, broad beans, courgettes, lettuce, new potatoes, peas, radishes, spinach, beetroot",
        "strawberries, cherries, gooseberries, elderflower"),
    7: ("broad beans, courgettes, cucumber, French beans, fennel, lettuce, peas, new potatoes, tomatoes, beetroot",
        "strawberries, raspberries, cherries, blackcurrants, redcurrants, gooseberries"),
    8: ("aubergine, courgettes, runner beans, French beans, sweetcorn, tomatoes, peppers, cucumber, beetroot",
        "blackberries, raspberries, plums, blueberries, early apples"),
    9: ("sweetcorn, runner beans, courgettes, tomatoes, marrow, squash, leeks, beetroot, peppers",
        "apples, pears, plums, damsons, blackberries, figs"),
    10: ("pumpkin, squash, celeriac, kale, leeks, parsnips, potatoes, beetroot, wild mushrooms",
         "apples, pears, quinces, sloes, chestnuts"),
    11: ("brussels sprouts, cabbage, celeriac, kale, leeks, parsnips, swede, pumpkin, Jerusalem artichokes",
         "apples, pears, quinces, cranberries (imported), chestnuts"),
    12: ("brussels sprouts, red cabbage, celeriac, kale, leeks, parsnips, swede, turnips",
         "apples (stored), pears (stored), clementines (imported), cranberries (imported)"),
}

# Grams per US cup for ingredients the unit converter (calcunits.DENSITY) doesn't already know.
CUPS = {
    "wholemeal flour": 120, "rye flour": 100, "cornflour": 120, "semolina": 165, "polenta": 160,
    "desiccated coconut": 80, "chopped nuts": 120, "walnuts": 100, "whole almonds": 145, "peanuts": 145,
    "peanut butter": 250, "maple syrup": 315, "treacle": 340, "raisins": 150, "sultanas": 150,
    "chocolate chips": 170, "grated cheese": 100, "grated parmesan": 90, "breadcrumbs": 110, "panko": 60,
    "couscous": 180, "quinoa": 170, "red lentils": 190, "frozen peas": 140, "chopped onion": 160,
    "spinach": 30, "berries": 150, "muesli": 110, "jam": 320, "mayonnaise": 230, "sesame seeds": 145,
    "chia seeds": 170, "cream cheese": 230, "dried pasta": 100, "pumpkin seeds": 130, "mashed banana": 225,
}

# (keywords, dish, wine, beer or cider, non-alcoholic)
PAIRINGS = [
    (["beef", "steak", "roast beef", "burger"], "Beef and steak", "Malbec, Cabernet Sauvignon, Rioja",
     "Porter or a bitter", "Blackcurrant cordial with soda, or a spiced cherry spritz"),
    (["lamb"], "Lamb", "Rioja, Pinot Noir, Côtes du Rhône", "Amber ale", "Pomegranate and mint spritzer"),
    (["pork", "sausage", "gammon", "ham"], "Pork and sausages", "Pinot Noir, dry Riesling, Beaujolais",
     "Dry cider", "Sparkling apple juice"),
    (["chicken", "roast chicken"], "Chicken", "Chardonnay, Pinot Noir, Viognier", "Golden ale or pale ale",
     "Elderflower pressé"),
    (["turkey", "christmas"], "Turkey and Christmas dinner", "Pinot Noir, Beaujolais, oaked Chardonnay",
     "Best bitter", "Cranberry and orange spritz"),
    (["duck", "game", "venison"], "Duck and game", "Pinot Noir, Syrah, Barolo", "Brown ale",
     "Cherry juice with sparkling water"),
    (["salmon", "trout"], "Salmon", "Pinot Noir, rosé, Chablis", "Wheat beer", "Lemonade with cucumber"),
    (["fish", "cod", "haddock", "fish and chips", "seabass"], "White fish", "Sauvignon Blanc, Albariño, Picpoul",
     "Pilsner or lager", "Sparkling water with lemon, or cloudy lemonade"),
    (["prawn", "shellfish", "mussels", "seafood", "crab"], "Shellfish", "Muscadet, Albariño, Champagne",
     "Belgian wheat beer", "Ginger and lime soda"),
    (["tomato pasta", "bolognese", "lasagne", "spaghetti", "pizza", "pasta"], "Tomato pasta and pizza",
     "Chianti, Montepulciano, Sangiovese", "Italian lager", "San Pellegrino-style blood orange soda"),
    (["carbonara", "creamy pasta", "risotto", "mac and cheese"], "Creamy pasta and risotto",
     "Pinot Grigio, Chardonnay, Soave", "Pale ale", "Apple and elderflower pressé"),
    (["curry", "tikka", "korma", "dal", "biryani", "indian"], "Curry", "Off-dry Riesling, Gewürztraminer, rosé",
     "Indian lager or IPA", "Mango lassi, or lime and soda"),
    (["chinese", "stir fry", "sweet and sour", "noodles"], "Chinese and stir-fries", "Off-dry Riesling, Pinot Gris",
     "Crisp lager", "Jasmine iced tea"),
    (["thai", "green curry", "pad thai"], "Thai", "Gewürztraminer, Riesling, Sauvignon Blanc", "Light lager",
     "Lemongrass and ginger soda"),
    (["mexican", "tacos", "chilli", "fajitas", "burrito"], "Mexican and chilli", "Zinfandel, Malbec, rosé",
     "Mexican lager with lime", "Agua fresca or lime and soda"),
    (["bbq", "barbecue", "ribs", "pulled pork"], "Barbecue", "Zinfandel, Shiraz", "Smoked porter or IPA",
     "Cream soda or iced tea"),
    (["mushroom", "vegetarian", "nut roast", "vegan"], "Mushroom and vegetarian roasts", "Pinot Noir, Beaujolais",
     "Brown ale", "Kombucha or sparkling apple"),
    (["salad", "goats cheese", "summer"], "Salads", "Sauvignon Blanc, rosé", "Wheat beer", "Cucumber and mint cooler"),
    (["cheese", "cheeseboard"], "Cheese board", "Port, Tawny, Sauternes, Rioja", "Barley wine or cider",
     "Grape juice or pear juice"),
    (["chocolate", "brownie", "chocolate cake"], "Chocolate puddings", "Tawny port, Banyuls, Pedro Ximénez",
     "Imperial stout", "Cold brew coffee or cherry cola"),
    (["fruit", "crumble", "tart", "pavlova", "trifle"], "Fruit puddings", "Moscato, late-harvest Riesling",
     "Fruit cider", "Elderflower cordial with sparkling water"),
    (["spicy", "jerk", "caribbean"], "Hot and spicy", "Off-dry Riesling, Grenache", "Crisp lager",
     "Ginger beer (non-alcoholic)"),
]
