"""Built-in DIY reference: how-to guides, safety reminders, drill and screw sizes, wall fixings, paint and stain guides.

UK homes and terms (consumer unit, stopcock, Gas Safe). General guidance only; when a guide says call a professional,
do that.
"""

# name: (minutes, difficulty, tools, safety, steps, call a professional if)
GUIDES = {
    "bleed a radiator": (15, "easy", ["radiator key", "old towel", "small bowl"],
        ["Turn the heating off and let the radiator cool first; hot water can scald.",
         "Put a towel under the valve to catch drips."],
        ["Find which radiators are cold at the top and warm at the bottom; those have trapped air.",
         "Switch the heating off and wait until the radiators are cool.",
         "Hold the towel under the bleed valve, at the top corner on one end.",
         "Fit the radiator key on the valve and turn it a quarter turn anticlockwise.",
         "Listen for the hiss of air. Keep hold of the key.",
         "Close the valve as soon as water starts to spit out.",
         "Wipe up, then check the boiler pressure gauge is between 1 and 2 bar.",
         "Top up the pressure with the filling loop if it dropped, then switch the heating on."],
        "The radiator keeps filling with air, or is cold in the middle (sludge)."),
    "change a fuse": (10, "easy", ["small screwdriver", "spare fuse of the right rating"],
        ["Unplug the appliance from the wall before opening the plug.",
         "Use the right fuse: 3 amp up to 700 W (lamps, TVs), 5 amp up to 1000 W, 13 amp above that (kettles, heaters)."],
        ["Unplug the plug from the socket and pull it out of the appliance.",
         "Undo the screw on the back of the plug and lift off the cover.",
         "Pop out the old fuse with the screwdriver and look at the rating printed on the appliance.",
         "Press in a new fuse of the right rating (3, 5 or 13 amp).",
         "Check the cable grip is tight and the wires are firmly held.",
         "Refit the cover and screw it closed, then test the appliance."],
        "The new fuse blows straight away; the appliance is faulty."),
    "unblock a sink": (20, "easy", ["washing-up gloves", "cup plunger", "bucket", "sink or bottle brush"],
        ["Never mix drain cleaners, and keep them away from your eyes and skin.",
         "Wear gloves; drain water is dirty."],
        ["Remove any plug and lift out food from the plughole.",
         "Boil a kettle and pour a little hot water down the drain (not on plastic waste pipes if it is boiling and the pipe is old).",
         "Block the overflow with a wet cloth and plunge firmly ten times.",
         "If it's still slow, put a bucket under the U-bend, unscrew the trap by hand and clear it out.",
         "Refit the trap, run the hot tap and check for leaks.",
         "Flush with hot water and washing-up liquid to clear grease."],
        "More than one drain is slow, or water comes back up elsewhere."),
    "fix a dripping tap": (40, "medium", ["adjustable spanner", "flat screwdriver", "spare washer or cartridge", "old cloth"],
        ["Turn the water off at the isolating valve under the sink, or at the stopcock, and open the tap to drain it.",
         "Put the plug in so small parts can't fall down the drain."],
        ["Turn off the water at the isolating valve, then run the tap until it stops.",
         "Prise off the cap or cover on the top of the handle and undo the screw underneath.",
         "Lift off the handle and unscrew the metal cover with the spanner, using a cloth to protect the finish.",
         "Take out the valve or cartridge. Look at the rubber washer at the bottom: is it worn or split?",
         "Replace the washer or cartridge with the same size; take the old one to the shop to match it.",
         "Reassemble in reverse order, turn the water back on slowly and check for drips."],
        "It still drips after the new washer (worn seat), or the tap is a ceramic disc type you can't match."),
    "hang a picture level": (10, "easy", ["spirit level or a phone level app", "pencil", "tape measure", "hammer and picture hook or a screw and wall plug"],
        ["Check for pipes and cables before you drill or nail; see the safety reminders.",
         "Wear eye protection when drilling."],
        ["Hold the picture where you want it, then measure the height of the hanging wire or hooks when pulled tight.",
         "Mark the centre of the wall spot with a pencil, at about 145 cm to the middle of the picture.",
         "Measure down from the top of the picture to the wire, and mark that far below the centre point.",
         "Fit the hook or a plugged screw at your mark.",
         "Hang the picture and put the spirit level along the top; nudge it until the bubble is centred.",
         "Stick a small piece of blu tack on each bottom corner to keep it straight."],
        "The wall is crumbly or the picture is heavy: use a proper heavy-duty fixing."),
    "reset a tripped rcd": (10, "easy", ["torch", "your fingers"],
        ["Don't touch anything wet or damaged. If you smell burning, see sparks, or the switch won't stay up, stop.",
         "Don't reset it again and again; it's tripping for a reason."],
        ["Find the consumer unit (fuse box), usually near the front door, meter or under the stairs; use a torch.",
         "Check which switch is down: the RCD (the bigger switch with a test button) or a single circuit breaker.",
         "Switch off or unplug any appliances that were running when it tripped.",
         "Push the tripped switch fully down to OFF, then firmly up to ON.",
         "If it stays on, plug appliances back in one at a time to find the faulty one.",
         "If it trips again with nothing plugged in, or you can't find the cause, leave it off."],
        "It trips again straight away or won't reset. Call a registered electrician."),
    "turn off the water at the stopcock": (5, "easy", ["torch"],
        ["If water is near electrics, switch the power off at the consumer unit first, if it's safe to reach."],
        ["Find the stopcock: usually under the kitchen sink, or near where the mains pipe enters the house.",
         "Turn it clockwise (right) until it stops; don't force it.",
         "Open the cold taps to drain the pipes.",
         "Turn off the heating and immersion heater if the hot water tank has been drained.",
         "Once fixed, turn the stopcock back on slowly and check the joints."],
        "The stopcock is seized or you can't find it; call your water company or a plumber."),
    "patch a small hole in plasterboard": (60, "medium", ["filler knife", "sandpaper", "self-adhesive mesh patch", "multi-purpose filler", "paint"],
        ["Wear a dust mask when sanding.", "Check for cables and pipes behind the hole."],
        ["Brush away loose crumbs and dust around the hole.",
         "Stick the mesh patch over the hole, larger than the hole all round.",
         "Spread filler over the patch with the knife, pressing it into the mesh.",
         "Leave it to dry, then add a thin second coat that feathers out onto the wall.",
         "When completely dry, sand smooth with fine sandpaper.",
         "Seal with a coat of primer, then paint to match."],
        "The board is soaking wet or the hole is bigger than a fist; fit a proper plasterboard patch."),
    "reseal a bath": (90, "medium", ["sealant remover", "sharp scraper", "masking tape", "sanitary silicone", "sealant gun", "cloth"],
        ["Use ventilation; some sealants smell strong.", "Fill the bath with water first so it is at its weight."],
        ["Fill the bath with water so it sits at its lowest point when full.",
         "Cut and scrape out all the old sealant, then wipe with sealant remover.",
         "Clean the gap with a cloth and let it dry completely.",
         "Mask above and below the gap with tape, leaving a thin gap.",
         "Cut the nozzle at 45 degrees and squeeze an even bead along the gap.",
         "Smooth the bead with a wet finger or a sealant tool.",
         "Peel off the tape straight away, then leave the water in until the sealant has cured (about 24 hours)."],
        "The wall or floor behind the bath is soft or damp."),
    "paint a room": (240, "medium", ["dust sheets", "masking tape", "filler", "sandpaper", "brushes and roller", "primer and paint"],
        ["Ventilate the room and keep the window open.",
         "Older homes (before the 1980s) may have lead paint, and older textured coatings may contain asbestos: don't sand them dry."],
        ["Move furniture out or into the middle and cover it and the floor with dust sheets.",
         "Fill holes and cracks, let dry, and sand smooth.",
         "Wash walls with sugar soap and let them dry.",
         "Tape round switches, sockets and woodwork, and remove the covers.",
         "Paint the ceiling first, then cut in along edges with a brush.",
         "Roll the walls in overlapping 'W' strokes, working towards a wet edge.",
         "Leave to dry as long as the tin says, then apply the second coat.",
         "Peel off the tape while the last coat is still slightly tacky."],
        "You find crumbling old plaster, damp, or suspect asbestos."),
    "hang a shelf": (30, "medium", ["drill", "masonry or wood bits", "wall plugs", "screws", "spirit level", "cable and pipe detector", "pencil"],
        ["Scan the wall for pipes and cables first.", "Wear goggles and a dust mask when you drill."],
        ["Decide the height, and check with the detector that it's clear of pipes, cables and studs.",
         "Hold the bracket up with the spirit level and mark the first hole.",
         "Drill using the right bit for the wall (masonry for brick, plain for plasterboard with a fixing) and tape the bit for depth.",
         "Push in a wall plug and screw the bracket up loosely.",
         "Check level, mark the second hole, then drill and fix.",
         "Fix all brackets, tighten, sit the shelf on and check it is level.",
         "Load it up slowly and keep heavy things near the brackets."],
        "You aren't sure what's behind the wall, or you want to hold heavy things like books on plasterboard."),
    "unblock a toilet": (20, "easy", ["toilet plunger (flanged)", "rubber gloves", "old towels", "bucket"],
        ["Never mix drain chemicals, and don't flush again if the bowl is nearly full.",
         "Wear gloves and put towels down."],
        ["Stop flushing and put towels around the base.",
         "Put the plunger in so it seals over the hole at the bottom of the bowl.",
         "Push down gently first to push out the air, then plunge firmly up and down about ten times.",
         "If the water goes down, flush once to test.",
         "If it doesn't, repeat a few times; add hot (not boiling) water and washing-up liquid.",
         "Wash your hands and the plunger with disinfectant."],
        "It won't clear after a few tries, or other drains are gurgling; it may be a drain blockage."),
}

# topic: (title, [points])
SAFETY = {
    "before you drill": ("Before you drill into a wall", [
        "Scan the spot with a cable, pipe and stud detector; run it in more than one direction.",
        "Cables usually run straight up and down or side to side from sockets and switches: avoid a 150 mm strip around them.",
        "Don't drill above or below a socket or switch, or in line with the top of a radiator.",
        "Take extra care near a boiler, meters, radiators and taps: pipes usually run straight to and from them.",
        "Use a drill with a depth stop or tape on the bit, and wear eye protection.",
        "If you hit something or see sparks or water, stop and turn off the power or water."]),
    "electrics": ("Electrical safety", [
        "Turn off the power at the consumer unit and check with a tester before you touch any wires.",
        "In England and Wales, new circuits and work in bathrooms, and changing a consumer unit, must be done by a registered electrician.",
        "Never work on live wires. Never use water on an electrical fire.",
        "Test your smoke alarms and the RCD test button regularly.",
        "Use an RCD-protected socket outdoors."]),
    "gas": ("Gas safety", [
        "Only a Gas Safe registered engineer should work on gas pipes and appliances.",
        "If you smell gas: open the windows, turn off the gas at the meter, don't touch switches, and call the National Gas Emergency line on 0800 111 999.",
        "Have appliances serviced once a year, and have a carbon monoxide alarm."]),
    "water": ("Water and plumbing", [
        "Know where your stopcock is, and check it turns.",
        "Turn off the water and drain the pipes before cutting or undoing any joint.",
        "Turn off the heating and immersion heater before draining a system.",
        "Water near electrics: switch the power off first if it's safe to reach the consumer unit."]),
    "ladders": ("Ladders and working at height", [
        "Use a ladder for short jobs, and have someone hold the foot if you can.",
        "Set it at the 1 in 4 rule: 1 metre out for every 4 metres up.",
        "Keep three points of contact, and don't reach: move the ladder instead.",
        "Never stand on the top three rungs, and check the feet are level and firm."]),
    "asbestos": ("Asbestos", [
        "Homes built before 2000 may contain asbestos in old textured coatings (Artex), floor tiles, ceiling tiles, pipe lagging and garage roofs.",
        "Don't drill, sand, scrape or break anything that could contain asbestos.",
        "If in doubt, stop, keep people away and get a test or a licensed contractor."]),
    "lead paint": ("Lead paint and dust", [
        "Paint in homes built before the 1980s may contain lead.",
        "Don't dry-sand or burn it off; use a damp cloth and a lead test kit if in doubt.",
        "Keep children and pregnant women out of the room, and clean with a damp cloth, not a dry brush."]),
    "dust and fumes": ("Dust, fumes and chemicals", [
        "Wear an FFP2 or FFP3 mask for sanding and cutting plasterboard, wood and masonry: the dust harms your lungs.",
        "Open windows when using paint, sealant, glue or spray, and keep them away from flames.",
        "Never mix cleaning chemicals, and keep them out of children's reach."]),
    "power tools": ("Power tools", [
        "Wear safety glasses, ear defenders and gloves that can't get caught in the tool.",
        "Unplug or remove the battery when changing blades or bits.",
        "Clamp the work down, and keep your hands behind the blade.",
        "Use an RCD plug outdoors, and keep the cable behind you."]),
    "lifting": ("Lifting and carrying", [
        "Bend your knees, keep the load close, and don't twist.",
        "Plasterboard, paving and bags of cement are heavy: get help or use a trolley.",
        "Wear steel-toe boots for heavy jobs."]),
}

# material: (bit, speed, tips)
DRILL_BITS = [
    ("Wood", "Twist or brad-point bit", "Fast", "Brad-point bits stop the bit wandering; clamp a block behind to avoid splintering."),
    ("Metal", "HSS twist bit", "Slow, with oil", "Start with a small pilot hole and a centre punch mark."),
    ("Brick and block", "Masonry bit, hammer action", "Medium", "Hammer drill on. Pull out often to clear dust."),
    ("Concrete", "SDS-plus bit in an SDS drill", "Medium to fast", "Use an SDS drill for holes larger than 8 mm."),
    ("Ceramic tile", "Tile or spear-point bit", "Slow, no hammer", "Put tape on the tile so the bit doesn't skate; drill through, then swap to masonry."),
    ("Glass or mirror", "Glass and tile bit", "Very slow", "Keep it wet with water and use light pressure. Best left to a glazier."),
    ("Plasterboard", "Wood or HSS bit", "Slow", "Use a fixing such as a plasterboard plug; don't hammer-drill."),
    ("Plastic", "Twist bit", "Slow", "Fast drills can melt plastic; back off often."),
    ("Large holes in wood", "Spade or hole saw", "Medium", "Drill a pilot first, and clamp the work."),
]

# gauge, diameter, clearance, pilot softwood, pilot hardwood (mm)
SCREWS = [
    ("No. 4", 2.8, 3.0, 1.5, 2.0), ("No. 6", 3.5, 4.0, 2.0, 2.5), ("No. 8", 4.0, 5.0, 2.5, 3.0),
    ("No. 10", 4.8, 5.5, 3.0, 3.5), ("No. 12", 5.5, 6.0, 3.5, 4.0), ("No. 14", 6.3, 6.5, 4.0, 4.5),
]

# wall: (fixing, drill, notes)
FIXINGS = [
    ("Brick or solid block", "Wall plug (brown 7 mm for No. 8 to 12 screws)", "Masonry bit with hammer action", "Plug colours vary by maker; check the pack. Bit size = plug size."),
    ("Concrete", "Frame fixing or concrete screw", "SDS bit", "Wear a mask; the dust is bad for lungs."),
    ("Plasterboard, light loads", "Plasterboard plug or self-drilling fixing", "Small twist bit or none", "Good for pictures and small shelves up to a few kilos."),
    ("Plasterboard, heavier loads", "Spring toggle or gravity toggle", "Twist bit", "Or fix into a stud or a batten behind. Check the weight rating on the pack."),
    ("Stud wall", "Wood screw into the timber stud", "Wood bit", "Find the stud with a detector, and check for cables."),
    ("Aircrete block", "Aircrete-specific fixing", "Twist bit, no hammer", "Standard plugs can pull out."),
    ("Old lath and plaster", "Toggle or screw into a joist or batten", "Slow, no hammer", "Plaster crumbles easily; find timber behind."),
    ("Tiled wall", "Plug after drilling through the tile", "Tile bit, then masonry bit", "Put tape on the tile and drill slowly with no hammer."),
]

# finish: (sheen, best for, notes)
FINISHES = [
    ("Flat matt", "Very low", "Ceilings and low-traffic walls", "Hides flaws, but marks easily and is hard to wipe."),
    ("Matt or soft matt", "Low", "Living rooms and bedrooms", "The most popular wall finish; washable matt is best for busy rooms."),
    ("Mid sheen or silk", "Medium", "Kitchens, bathrooms, hallways", "Wipes clean and resists steam; shows wall flaws."),
    ("Eggshell", "Low to medium", "Woodwork and radiators", "A soft glow, tough and easy to clean."),
    ("Satin", "Medium to high", "Woodwork, doors and trim", "Durable with a gentle shine."),
    ("Gloss", "High", "Doors, skirting and metalwork", "Very tough and shiny; shows every dent, and needs a good undercoat."),
    ("Kitchen and bathroom paint", "Low to medium", "Damp, steamy rooms", "Has mould resistance and wipes clean."),
    ("Masonry paint", "Low", "Outside walls", "Weatherproof; breathable types suit older brick and render."),
]

# type: (look, best for, notes)
STAINS = [
    ("Water-based wood stain", "Colour with little smell", "Interior furniture and trim", "Dries fast; raises the grain, so sand lightly between coats."),
    ("Oil-based wood stain", "Rich, deep colour", "Interior wood and doors", "Soaks in well but has a strong smell and dries slowly."),
    ("Wood dye", "Colour that shows the grain", "Indoor timber", "Needs varnish or wax on top."),
    ("Decking oil", "Natural, enhances grain", "Decking and garden furniture", "Reapply every year; clean first with decking cleaner."),
    ("Decking stain", "Coloured protection", "Decking", "Lasts longer than oil on shady, damp boards."),
    ("Fence paint or treatment", "Colour and protection", "Sheds and fences", "Apply in dry weather; two coats last around 5 years."),
    ("Danish or teak oil", "Warm, natural", "Hardwood furniture and worktops", "Wipe on thin coats, and rub off the extra."),
    ("Wood varnish", "Clear or tinted, hard-wearing", "Floors, doors and furniture", "Sand lightly between coats, and use polyurethane on floors."),
    ("Wax", "Soft, natural feel", "Furniture and bare floors", "Gentle but wears off; polish now and then."),
]
