"""The beginner learning path: ten short lessons, each with a three-question quiz. Education only, no product picks."""

LESSONS = [
    {"id": "what-is-investing", "title": "What investing is",
     "body": ["Saving keeps money safe for soon. Investing puts money into things like company shares or bonds that can grow over time, but can also fall.",
              "You are paid for waiting and for taking risk, with no guarantee. You can get back less than you put in.",
              "Money you need within a few years usually belongs in savings, not investments."],
     "quiz": [("Which is true of investing?", ["Returns are guaranteed", "You can get back less than you put in", "It has no risk"], 1, "Capital is at risk with any investment."),
              ("Money needed in two years is usually better placed...", ["In shares", "In easy-access savings", "In a friend's tip"], 1, "Short time horizons leave no time to recover from a fall."),
              ("What does an investor hope to be paid for?", ["Waiting and taking risk", "Being lucky", "A guaranteed bonus"], 0, "Returns are compensation for time and risk, never certain.")]},
    {"id": "compound-growth", "title": "Compound growth",
     "body": ["Growth on top of growth. 1,000 pounds growing at 5% a year becomes about 4,320 after 30 years, if it did so every year.",
              "Real returns are not smooth and can be negative some years.",
              "Time in the market does most of the work, so starting early helps even with small amounts."],
     "quiz": [("Compounding means...", ["Growth earning its own growth", "A fee", "A tax"], 0, "Each gain is added to the pot and then grows too."),
              ("What helps compounding most?", ["Time", "A lucky tip", "Checking daily"], 0, "Longer time gives more rounds of growth."),
              ("Real investment returns are...", ["Smooth every year", "Uneven, with some bad years", "Fixed by law"], 1, "Illustrations use a steady rate, real life does not.")]},
    {"id": "risk-and-reward", "title": "Risk and reward",
     "body": ["Higher possible return usually means higher risk of loss. Cash rarely falls in price but can lose to inflation; shares swing more.",
              "Risk tolerance is how you feel about falls; capacity for loss is what you can afford.",
              "Never invest money you cannot afford to lose."],
     "quiz": [("Higher potential returns usually come with...", ["Higher risk", "Lower risk", "A guarantee"], 0, "There is no free lunch."),
              ("Capacity for loss is about...", ["Your circumstances", "Your mood", "The news"], 0, "It is what you could afford to lose."),
              ("Which assets usually swing the most in price?", ["Cash", "Shares", "The same as each other"], 1, "Shares are more volatile than cash or high quality bonds.")]},
    {"id": "inflation", "title": "Inflation",
     "body": ["Prices rise over time so each pound buys less. At 2.5% a year, what costs 100 pounds now costs about 210 in 30 years.",
              "Real return is return minus inflation. Cash earning less than inflation loses buying power slowly.",
              "The inflation-adjusted line in the calculators shows growth in today's money."],
     "quiz": [("Inflation makes money...", ["Buy less over time", "Buy more", "Vanish overnight"], 0, "Prices rise so the same pound buys less."),
              ("Real return equals...", ["Return minus inflation", "Return plus fees", "The headline number"], 0, "It shows change in buying power."),
              ("Cash paying less than inflation is...", ["Growing in real terms", "Losing buying power", "Guaranteed to win"], 1, "It falls behind prices.")]},
    {"id": "fees", "title": "Fees and charges",
     "body": ["Charges come off every year and compound against you. 1% instead of 0.2% over 30 years can cost a large slice of the final pot.",
              "Look at fund charges (OCF), platform fees, dealing fees and the spread.",
              "Lower cost does not guarantee better results, but cost is one thing you can control."],
     "quiz": [("Fees are taken...", ["Only when you profit", "Whether or not it grows", "Only when you sell"], 1, "Yearly charges apply regardless of performance."),
              ("The OCF is...", ["A yearly fund charge", "A tax", "A bonus"], 0, "Ongoing charges figure."),
              ("Which cost can you influence?", ["Market returns", "The charges you choose to pay", "Inflation"], 1, "Comparing costs is in your hands.")]},
    {"id": "diversification", "title": "Diversification",
     "body": ["Spreading across many companies, countries and types of asset means one failure hurts less.",
              "Funds spread money for you. Own many things, not many copies of the same thing.",
              "It lowers the risk of a single failure but cannot stop the whole market falling."],
     "quiz": [("Diversification aims to...", ["Remove all risk", "Reduce the damage from one thing failing", "Guarantee profit"], 1, "It spreads risk, not removes it."),
              ("A fund helps by...", ["Holding many investments at once", "Guaranteeing returns", "Avoiding fees"], 0, "It pools lots of holdings."),
              ("In a big market fall, diversified holdings...", ["Never fall", "Can still fall together", "Always rise"], 1, "Broad falls hit most things.")]},
    {"id": "uk-wrappers", "title": "ISAs and pensions",
     "body": ["A wrapper is a tax shell around savings or investments. ISAs have a yearly allowance and tax-free growth. Pensions add tax relief and often employer money but are locked until pension age.",
              "A Lifetime ISA adds a 25% bonus but has a penalty for withdrawing early for the wrong reasons.",
              "Limits change: check GOV.UK for the current ones."],
     "quiz": [("Growth inside an ISA is...", ["Free of UK income and capital gains tax", "Guaranteed", "Insured against falls"], 0, "That is the tax wrapper benefit; value can still fall."),
              ("A pension is usually...", ["Locked until minimum pension age", "Available any time", "Risk free"], 0, "Access is restricted."),
              ("Where should you check current limits?", ["GOV.UK", "A social media post", "A cold caller"], 0, "Official rules change; use the official source.")]},
    {"id": "emergency-first", "title": "Emergency fund first",
     "body": ["Keep easy-access savings for surprises, often three to six months of essentials, before putting money into things that can fall.",
              "Otherwise a shock could force you to sell at a bad moment or borrow.",
              "Expensive debt matters too. What comes first depends on your situation."],
     "quiz": [("An emergency fund is for...", ["Surprises", "Investing in shares", "Holiday shopping"], 0, "It is a buffer against shocks."),
              ("It is usually held in...", ["Easy-access cash", "Locked pension", "Risky investments"], 0, "You need it quickly and at full value."),
              ("Why before investing?", ["To avoid forced selling in a downturn", "To get guaranteed profit", "Because the law says so"], 0, "Investments may be down when you need cash.")]},
    {"id": "regular-vs-lump", "title": "Regular saving and lump sums",
     "body": ["Pound-cost averaging means investing a fixed amount on a schedule. You buy more units when prices are low and fewer when high.",
              "It does not guarantee profit and often trails a lump sum in rising markets, but it makes a habit and removes timing worry.",
              "Nobody can reliably time the market."],
     "quiz": [("Pound-cost averaging is...", ["Investing fixed amounts regularly", "A guaranteed strategy", "A fee"], 0, "Regular, fixed instalments."),
              ("It ...", ["Guarantees a profit", "Does not remove the risk of loss", "Cannot lose"], 1, "Capital is at risk however you invest."),
              ("Can people reliably time the market?", ["Yes", "No, not reliably", "Only with an app"], 1, "Timing consistently is extremely hard.")]},
    {"id": "spot-scams", "title": "Spotting investment scams",
     "body": ["Red flags: guaranteed returns, pressure to act fast, cold contact, celebrity adverts, secrecy, unusual payment methods.",
              "Check any firm on the FCA Register using details you find yourself. Beware clone firms copying real ones.",
              "If unsure, stop and talk to someone you trust. Report scams via Action Fraud or the FCA."],
     "quiz": [("'Guaranteed 20% a month' is...", ["A great deal", "A classic scam sign", "Normal"], 1, "No legitimate investment can guarantee returns."),
              ("Where do you check a firm is authorised?", ["The FCA Register", "The firm's own leaflet", "A stranger's message"], 0, "Use contact details from the Register itself."),
              ("What is a clone firm?", ["A scam copying a real firm", "A cheap fund", "A type of ISA"], 0, "Scammers borrow real firms' names and details.")]},
]
