"""Built-in lists for the kids abilities: activity ideas, clean jokes, tongue twisters, story parts, lunch ideas."""

# (idea, where: indoor/outdoor, good on a rainy day, costs nothing, youngest age, oldest age)
ACTIVITIES = [
    ("Build a blanket fort and read in it with a torch", "indoor", True, True, 3, 11),
    ("Have a teddy bears' picnic on the living room floor", "indoor", True, True, 2, 7),
    ("Make a paper plate mask of a favourite animal", "indoor", True, True, 3, 9),
    ("Bake and decorate simple biscuits", "indoor", True, False, 3, 12),
    ("Put on a puppet show with socks", "indoor", True, True, 3, 10),
    ("Play hide and seek around the house", "indoor", True, True, 3, 10),
    ("Make a marble run from toilet roll tubes and tape", "indoor", True, True, 5, 12),
    ("Do a jigsaw puzzle together", "indoor", True, True, 3, 14),
    ("Have a family board game tournament", "indoor", True, True, 5, 16),
    ("Draw a comic strip about the family pet or a made-up hero", "indoor", True, True, 6, 14),
    ("Make playdough from flour, salt and water", "indoor", True, True, 2, 8),
    ("Have a dance party with a freeze game", "indoor", True, True, 2, 10),
    ("Build the tallest tower you can from cups or blocks", "indoor", True, True, 2, 9),
    ("Write and post a letter to a grandparent", "indoor", True, False, 5, 12),
    ("Do a floor-is-lava obstacle course with cushions", "indoor", True, True, 3, 10),
    ("Make a fruit smoothie and name it", "indoor", True, False, 4, 14),
    ("Learn a simple card trick and perform it", "indoor", True, True, 6, 16),
    ("Have an indoor treasure hunt with picture clues", "indoor", True, True, 3, 9),
    ("Make a family time capsule in a shoebox", "indoor", True, True, 5, 14),
    ("Try a kids' yoga video together", "indoor", True, True, 3, 12),
    ("Grow cress on damp kitchen roll", "indoor", True, False, 3, 9),
    ("Make a den from cardboard boxes", "indoor", True, True, 3, 10),
    ("Have a cinema afternoon with homemade tickets and popcorn", "indoor", True, False, 3, 14),
    ("Do a science experiment: vinegar and bicarbonate volcano", "indoor", True, False, 4, 11),
    ("Play shops with tins from the cupboard and pretend money", "indoor", True, True, 3, 8),
    ("Make a family tree with photos or drawings", "indoor", True, True, 6, 14),
    ("Learn to fold a paper aeroplane and hold a flying contest", "indoor", True, True, 5, 14),
    ("Paint pebbles or stones from the garden", "indoor", True, False, 3, 12),
    ("Write a short play and act it out", "indoor", True, True, 7, 16),
    ("Build a Lego or brick challenge: make a vehicle in 10 minutes", "indoor", True, True, 4, 14),
    ("Go on a nature scavenger hunt: a feather, a pine cone, a red leaf", "outdoor", False, True, 3, 11),
    ("Go puddle jumping in wellies and waterproofs", "outdoor", True, True, 2, 9),
    ("Have a picnic at the park", "outdoor", False, False, 2, 16),
    ("Ride bikes or scooters on a traffic-free path", "outdoor", False, True, 4, 16),
    ("Draw a hopscotch grid with chalk and play", "outdoor", False, False, 4, 10),
    ("Go bug hunting with a magnifying glass", "outdoor", False, True, 3, 10),
    ("Feed the ducks with oats or peas (not bread)", "outdoor", False, False, 2, 8),
    ("Fly a kite on a windy day", "outdoor", False, False, 4, 14),
    ("Do a rain walk and listen to the sounds", "outdoor", True, True, 3, 12),
    ("Make a mud kitchen in the garden", "outdoor", True, True, 2, 7),
    ("Visit the library and choose three books", "outdoor", True, True, 2, 14),
    ("Play football or rounders at the park", "outdoor", False, True, 5, 16),
    ("Go blackberry picking in late summer", "outdoor", False, True, 4, 14),
    ("Build a stick den in the woods", "outdoor", False, True, 5, 14),
    ("Make a leaf rubbing collection with crayons", "outdoor", False, True, 3, 10),
    ("Have a water fight on a hot day", "outdoor", False, True, 3, 14),
    ("Plant seeds or bulbs in a pot or the garden", "outdoor", False, False, 3, 12),
    ("Go to a free museum", "indoor", True, True, 4, 16),
    ("Look for shapes in the clouds lying on a blanket", "outdoor", False, True, 3, 12),
    ("Go star gazing after dark and find the Plough", "outdoor", False, True, 5, 16),
    ("Have a sponge race relay with buckets", "outdoor", False, True, 4, 12),
    ("Go on a bear hunt walk, acting out the story", "outdoor", False, True, 2, 6),
    ("Take photos on a colour walk: find something of every colour", "outdoor", False, True, 5, 14),
    ("Make a bird feeder from a pine cone and seeds", "outdoor", False, False, 4, 11),
    ("Play I-spy on a walk to the shops", "outdoor", True, True, 3, 8),
    ("Go swimming at the local pool", "indoor", True, False, 3, 16),
    ("Cook a simple lunch together: wraps or pizza toast", "indoor", True, False, 5, 16),
    ("Do a litter pick in the park with gloves", "outdoor", False, True, 6, 16),
    ("Build a sandcastle or sandpit city", "outdoor", False, True, 2, 10),
    ("Make a rainy day wind chime from old spoons and string", "indoor", True, True, 6, 14),
]

JOKES = [
    ("What do you call a dinosaur that is sleeping?", "A dino-snore!"),
    ("Why did the teddy bear say no to pudding?", "Because she was stuffed."),
    ("What do you call a fish with no eyes?", "A fsh."),
    ("Why can't a bicycle stand up by itself?", "Because it's two tired."),
    ("What did the ocean say to the beach?", "Nothing, it just waved."),
    ("What do you get when you cross a snowman with a vampire?", "Frostbite."),
    ("Why did the cookie go to the doctor?", "Because it felt crummy."),
    ("What has ears but cannot hear?", "A field of corn."),
    ("What do cows read in the morning?", "The moos-paper."),
    ("Why are ghosts bad at telling lies?", "Because you can see right through them."),
    ("What do you call a bear with no teeth?", "A gummy bear."),
    ("Why did the banana go to the doctor?", "Because it wasn't peeling well."),
    ("What's orange and sounds like a parrot?", "A carrot."),
    ("How do you make an octopus laugh?", "With ten-tickles."),
    ("What do elves learn at school?", "The elf-abet."),
    ("Why did the scarecrow win a prize?", "Because he was outstanding in his field."),
    ("What do you call a sleeping bull?", "A bulldozer."),
    ("Where do sheep go for a haircut?", "To the baa-baa shop."),
    ("What kind of tree fits in your hand?", "A palm tree."),
    ("Why did the student eat his homework?", "Because the teacher said it was a piece of cake."),
    ("What do you call a pig that does karate?", "A pork chop."),
    ("What did one plate say to the other?", "Dinner's on me."),
    ("Why do bees have sticky hair?", "Because they use honeycombs."),
    ("What is a cat's favourite colour?", "Purr-ple."),
    ("What do you call a dog magician?", "A labracadabrador."),
    ("Why was the maths book sad?", "It had too many problems."),
    ("What do you call a train carrying bubblegum?", "A chew-chew train."),
    ("What falls in winter but never gets hurt?", "Snow."),
    ("How does the moon cut his hair?", "Eclipse it."),
    ("What do frogs order at a cafe?", "French flies."),
    ("Why did the golfer bring two pairs of trousers?", "In case he got a hole in one."),
    ("What did the left eye say to the right eye?", "Between you and me, something smells."),
    ("What's a ghost's favourite pudding?", "I scream."),
    ("Why do fish live in salt water?", "Because pepper makes them sneeze."),
    ("What do you call a lazy kangaroo?", "A pouch potato."),
    ("What did the big flower say to the little flower?", "Hi, bud!"),
    ("Why did the owl invite his friends over?", "He didn't want to be owl by himself."),
    ("What kind of music do mummies like?", "Wrap music."),
    ("What do you call a duck that gets all A's?", "A wise quacker."),
    ("Why did the tomato turn red?", "Because it saw the salad dressing."),
    ("What does a cloud wear under its raincoat?", "Thunderwear."),
    ("How do you talk to a giant?", "Use big words."),
    ("What animal needs to wear a wig?", "A bald eagle."),
    ("Why don't eggs tell jokes?", "They'd crack each other up."),
    ("What did the zero say to the eight?", "Nice belt!"),
    ("What do you call a boomerang that doesn't come back?", "A stick."),
    ("Why was the broom late?", "It over-swept."),
    ("What do you call a cow with no legs?", "Ground beef."),
    ("What's brown and sticky?", "A stick."),
    ("Knock knock. Who's there? Lettuce. Lettuce who?", "Lettuce in, it's cold out here!"),
]

TONGUE_TWISTERS = [
    "She sells seashells by the seashore.",
    "Red lorry, yellow lorry.",
    "Peter Piper picked a peck of pickled peppers.",
    "How can a clam cram in a clean cream can?",
    "Fred fed Ted bread, and Ted fed Fred bread.",
    "Six slippery snails slid slowly seaward.",
    "Betty Botter bought some butter, but she said the butter's bitter.",
    "Round the rugged rock the ragged rascal ran.",
    "Freshly fried flying fish.",
    "Unique New York, unique New York.",
    "Toy boat, toy boat, toy boat.",
    "Eleven benevolent elephants.",
    "A proper copper coffee pot.",
    "Big black bugs bleed blue black blood.",
    "Four fine fresh fish for you.",
    "Friendly fleas and fireflies.",
    "Green glass globes glow greenly.",
    "Silly Sally swiftly shooed seven silly sheep.",
    "I scream, you scream, we all scream for ice cream.",
    "Can you can a can as a canner can can a can?",
    "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair.",
    "Lucky rabbits like to cause a ruckus.",
    "Wayne went to Wales to watch walruses.",
    "Chester cheetah chews a chunk of cheap cheddar cheese.",
    "Pad kid poured curd pulled cod.",
    "Truly rural, truly rural.",
    "Stupid superstition.",
    "A big bug bit the little beetle.",
    "Three free throws.",
    "Wendy's white wheels went wobbly on Wednesday.",
]

STORY_HEROES = ["a brave little fox", "a clever robot called Bolt", "a kind dragon who can't breathe fire",
                "a sleepy owl", "a tiny knight", "a curious rabbit", "a friendly giant", "a young astronaut",
                "a unicorn who loves maths", "a cheeky penguin", "a pirate who is scared of water",
                "a princess who fixes machines"]
STORY_SIDEKICKS = ["a chatty parrot", "a wise old tortoise", "a bouncy puppy", "a shy hedgehog",
                   "a glowing firefly", "a talking teapot", "a helpful cloud", "a grumpy but kind cat"]
STORY_PLACES = ["an enchanted forest", "a castle in the clouds", "an underwater city", "the Moon",
                "a sweet shop that never closes", "a snowy mountain village", "a secret garden",
                "a jungle full of singing birds", "a lighthouse by the sea", "a toy shop at midnight",
                "a desert island", "a library where books come alive"]
STORY_THEMES = {
    "friendship": ("making a new friend who seems different", "friends help each other"),
    "bravery": ("being scared of the dark", "being brave doesn't mean not being scared"),
    "kindness": ("someone who is lost and alone", "a small kindness can change a whole day"),
    "sharing": ("only one magic toy between two friends", "things are more fun when we share them"),
    "adventure": ("a map with a missing piece", "the journey is the best part"),
    "trying again": ("a kite that just won't fly", "if at first you don't succeed, try again"),
    "honesty": ("a broken vase and a secret", "telling the truth makes us feel lighter"),
    "helping": ("a village whose river has dried up", "together we can fix big problems"),
    "calm": ("a storm that keeps everyone awake", "slow breaths help us feel calm and sleepy"),
}
STORY_OBJECTS = ["a golden key", "a map drawn in stars", "a whistle that calls the wind", "a glowing pebble",
                 "a pair of silver boots", "a jar of moonlight", "a feather that writes by itself",
                 "a shell that sings"]
STORY_TWISTS = ["the scary noise was only a hiccuping snail", "the treasure was a friendship all along",
                "the villain just wanted someone to play with", "the map was upside down the whole time",
                "the storm was a sleepy giant snoring", "the magic only worked when they laughed"]

LUNCH_IDEAS = [
    "Cheese and cucumber sandwich", "Ham and tomato wrap", "Tuna pasta salad", "Hummus with pitta and carrot sticks",
    "Egg mayo roll", "Chicken and sweetcorn wrap", "Cheese scone and grapes", "Pizza pinwheels",
    "Sausage roll and cherry tomatoes", "Cream cheese bagel", "Falafel and pitta pocket", "Pasta with pesto",
    "Crackers, cheese cubes and apple slices", "Leftover rice with peas and chicken", "Jam sandwich and a yoghurt",
]
