"""The quiz-night question bank: 150 family-friendly questions in ten categories, plus number tiebreakers.

Each entry is (question, answer). Nothing here goes online.
"""

QUESTIONS: dict[str, list[tuple[str, str]]] = {
    "General knowledge": [
        ("How many sides does a hexagon have?", "Six"),
        ("What colour do you get by mixing blue and yellow?", "Green"),
        ("How many days are there in a leap year?", "366"),
        ("Which planet is known as the Red Planet?", "Mars"),
        ("What is the largest ocean on Earth?", "The Pacific"),
        ("How many players from one team are on the pitch in a football match?", "Eleven"),
        ("What do bees make?", "Honey"),
        ("What is the chemical symbol for gold?", "Au"),
        ("How many strings does a standard guitar have?", "Six"),
        ("What is the hardest natural substance?", "Diamond"),
        ("In which month is Christmas Day?", "December"),
        ("How many letters are in the English alphabet?", "26"),
        ("What is frozen water called?", "Ice"),
        ("Which fruit is the main ingredient of guacamole?", "Avocado"),
        ("How many minutes are in two hours?", "120"),
    ],
    "Geography": [
        ("What is the capital of France?", "Paris"),
        ("Which is the longest river in Africa?", "The Nile"),
        ("What is the capital of Australia?", "Canberra"),
        ("Which country is home to the kangaroo?", "Australia"),
        ("What is the smallest country in the world?", "Vatican City"),
        ("Which continent is the Sahara Desert on?", "Africa"),
        ("What is the capital of Scotland?", "Edinburgh"),
        ("Which mountain is the highest in the world?", "Mount Everest"),
        ("What is the capital of Canada?", "Ottawa"),
        ("Which sea lies between Italy and the Balkans?", "The Adriatic Sea"),
        ("In which country would you find Machu Picchu?", "Peru"),
        ("What is the capital of Japan?", "Tokyo"),
        ("Which river flows through London?", "The Thames"),
        ("What is the largest country in the world by area?", "Russia"),
        ("Which is the largest island in the world?", "Greenland"),
    ],
    "History": [
        ("In which year did the Second World War end?", "1945"),
        ("Who was the first man to walk on the Moon?", "Neil Armstrong"),
        ("Which ancient civilisation built the pyramids at Giza?", "The Egyptians"),
        ("Which English king had six wives?", "Henry the Eighth"),
        ("In what year did the Titanic sink?", "1912"),
        ("Who was the British Prime Minister for most of the Second World War?", "Winston Churchill"),
        ("What was the name of the ship the Pilgrims sailed to America in 1620?", "The Mayflower"),
        ("Which Roman city was buried by the eruption of Vesuvius in 79 AD?", "Pompeii"),
        ("Which queen ruled Britain for 63 years, until 1901?", "Queen Victoria"),
        ("Which wall fell in Berlin in 1989?", "The Berlin Wall"),
        ("Who discovered penicillin?", "Alexander Fleming"),
        ("Which Roman emperor is said to have played the fiddle while Rome burned?", "Nero"),
        ("In which year did the Great Fire of London happen?", "1666"),
        ("Which explorer is credited with reaching the Americas in 1492?", "Christopher Columbus"),
        ("Who was the first woman to fly solo across the Atlantic?", "Amelia Earhart"),
    ],
    "Science": [
        ("What gas do plants take in from the air?", "Carbon dioxide"),
        ("How many planets are in our solar system?", "Eight"),
        ("What is the closest star to Earth?", "The Sun"),
        ("What is H2O more commonly known as?", "Water"),
        ("How many bones does an adult human have?", "206"),
        ("What force pulls objects towards the Earth?", "Gravity"),
        ("At what temperature in degrees Celsius does water boil at sea level?", "100"),
        ("Which organ pumps blood around the body?", "The heart"),
        ("What is the name of our galaxy?", "The Milky Way"),
        ("What do we call an animal that eats only plants?", "A herbivore"),
        ("What is the centre of an atom called?", "The nucleus"),
        ("Which planet has the most famous rings?", "Saturn"),
        ("What is the process by which a caterpillar becomes a butterfly?", "Metamorphosis"),
        ("What type of energy comes from the Sun?", "Solar energy"),
        ("What is the hardest substance in the human body?", "Tooth enamel"),
    ],
    "Nature and animals": [
        ("What is the fastest land animal?", "The cheetah"),
        ("What is a baby kangaroo called?", "A joey"),
        ("How many legs does a spider have?", "Eight"),
        ("What is the largest animal on Earth?", "The blue whale"),
        ("Which flightless bird lives in Antarctica?", "The penguin"),
        ("What do caterpillars turn into?", "Butterflies or moths"),
        ("What is a group of lions called?", "A pride"),
        ("Which animal is known as the ship of the desert?", "The camel"),
        ("How many hearts does an octopus have?", "Three"),
        ("What is the tallest animal in the world?", "The giraffe"),
        ("Which tree do acorns grow on?", "The oak"),
        ("What is a baby swan called?", "A cygnet"),
        ("What colour are the stripes on a zebra?", "Black and white"),
        ("Which mammal can fly?", "The bat"),
        ("What do giant pandas mainly eat?", "Bamboo"),
    ],
    "Food and drink": [
        ("Which country did pizza come from?", "Italy"),
        ("What is the main ingredient of hummus?", "Chickpeas"),
        ("Which nut is used to make marzipan?", "Almonds"),
        ("Which vegetable makes you cry when you chop it?", "The onion"),
        ("Which grain is sushi traditionally made with?", "Rice"),
        ("Which fruit is dried to make raisins?", "Grapes"),
        ("What is a Yorkshire pudding made from?", "Batter (eggs, flour and milk)"),
        ("What colour is a ripe banana?", "Yellow"),
        ("What do you call a British breakfast of eggs, bacon and sausage?", "A full English"),
        ("Which spice is the most expensive in the world by weight?", "Saffron"),
        ("What is the Italian word for ice cream?", "Gelato"),
        ("Which drink is made by steeping leaves in hot water?", "Tea"),
        ("What is the Japanese dish of thinly sliced raw fish called?", "Sashimi"),
        ("Which cheese is traditionally used in a Greek salad?", "Feta"),
        ("Which country is the croissant most famously associated with?", "France"),
    ],
    "Sport": [
        ("How many points is a touchdown worth in American football?", "Six"),
        ("In which sport would you perform a slam dunk?", "Basketball"),
        ("In which country are the Wimbledon tennis championships held?", "England"),
        ("How many rings are on the Olympic flag?", "Five"),
        ("In golf, what is one stroke under par called?", "A birdie"),
        ("How many players are in a cricket team?", "Eleven"),
        ("Which sport uses a shuttlecock?", "Badminton"),
        ("What is the maximum score in a single frame of ten-pin bowling?", "30"),
        ("In which sport do you score a try?", "Rugby"),
        ("How long is a marathon in miles, roughly?", "26.2 miles"),
        ("Which country won the 2022 FIFA World Cup?", "Argentina"),
        ("What colour jersey does the overall leader of the Tour de France wear?", "Yellow"),
        ("In darts, what is the highest score with three darts?", "180"),
        ("Which snooker ball is worth seven points?", "The black"),
        ("Which cricket ground in London is known as the home of cricket?", "Lord's"),
    ],
    "Music": [
        ("How many members were in the Beatles?", "Four"),
        ("Which instrument has 88 keys?", "The piano"),
        ("Which band sang 'Bohemian Rhapsody'?", "Queen"),
        ("Which Beethoven symphony ends with the 'Ode to Joy'?", "The Ninth"),
        ("Which singer is known as the Queen of Pop?", "Madonna"),
        ("What is the largest string instrument in an orchestra's string section that you play standing up?", "The double bass"),
        ("How many beats does a minim last in 4/4 time?", "Two"),
        ("Which British singer had a huge hit with 'Someone Like You'?", "Adele"),
        ("Which Swedish group sang 'Dancing Queen'?", "ABBA"),
        ("Which instrument does a drummer play?", "Drums"),
        ("What does the musical term 'piano' mean?", "Quietly"),
        ("Who composed 'The Four Seasons'?", "Vivaldi"),
        ("Which pop star released the album '1989'?", "Taylor Swift"),
        ("How many notes are in an octave, counting both ends?", "Eight"),
        ("Which brass instrument has a slide?", "The trombone"),
    ],
    "Film and TV": [
        ("Which film features a lion cub called Simba?", "The Lion King"),
        ("Which actor plays Captain Jack Sparrow?", "Johnny Depp"),
        ("What is the name of the wizard school in Harry Potter?", "Hogwarts"),
        ("Which Disney film features a snowman called Olaf?", "Frozen"),
        ("In Toy Story, what kind of toy is Woody?", "A cowboy"),
        ("What is the name of Shrek's donkey friend?", "Donkey"),
        ("Which sitcom is set around a coffee shop called Central Perk?", "Friends"),
        ("What was the name of Dorothy's dog in The Wizard of Oz?", "Toto"),
        ("Which yellow cartoon family live in Springfield?", "The Simpsons"),
        ("In which film does a clownfish search for his son?", "Finding Nemo"),
        ("What is the name of the space ranger toy in Toy Story?", "Buzz Lightyear"),
        ("Which British show features a Time Lord travelling in a blue police box?", "Doctor Who"),
        ("What colour is Kermit the Frog?", "Green"),
        ("Which boy never grows up in J. M. Barrie's story?", "Peter Pan"),
        ("Which film series follows a hobbit called Frodo?", "The Lord of the Rings"),
    ],
    "British life": [
        ("What is the currency of the UK?", "The pound sterling"),
        ("Which city is home to Big Ben?", "London"),
        ("On which date is Bonfire Night in the UK?", "5 November"),
        ("What is the address of the Prime Minister's official London home?", "10 Downing Street"),
        ("What do you call the traditional British afternoon meal of tea and scones?", "Afternoon tea"),
        ("Which of the four UK nations has a dragon on its flag?", "Wales"),
        ("What is the national flower of England?", "The rose"),
        ("What colour is a British post box?", "Red"),
        ("What is the name of the famous bell in the clock tower at Westminster?", "Big Ben"),
        ("What do the initials NHS stand for?", "National Health Service"),
        ("Which sport is the Six Nations championship played in?", "Rugby union"),
        ("What is the classic British takeaway of battered fish with what?", "Chips"),
        ("Which university does Oxford race in the annual Boat Race?", "Cambridge"),
        ("What is the highest mountain in England?", "Scafell Pike"),
        ("Which stone circle in Wiltshire is one of Britain's best-known landmarks?", "Stonehenge"),
    ],
}

TIEBREAKERS: list[tuple[str, int]] = [
    ("How many keys are on a standard piano?", 88),
    ("How many bones are in the adult human body?", 206),
    ("In what year did the Berlin Wall fall?", 1989),
    ("How many minutes are in a full day?", 1440),
    ("How many squares are on a chessboard?", 64),
    ("How many days are there in a year that is not a leap year?", 365),
    ("How many players are on the court for one team in basketball?", 5),
    ("In what year did the Titanic sink?", 1912),
]


def categories() -> list[str]:
    return list(QUESTIONS)


def total() -> int:
    return sum(len(v) for v in QUESTIONS.values())
