"""Party-game content: word cards, Taboo-style cards, truths and dares, icebreakers and Scattergories lists.

All family-friendly and built in; nothing goes online.
"""

WORDS: dict[str, list[str]] = {
    "animals": ["elephant", "penguin", "kangaroo", "giraffe", "crocodile", "butterfly", "octopus", "monkey", "snake",
                "flamingo", "hedgehog", "dolphin", "spider", "rabbit", "owl", "horse", "lion", "frog", "bat", "shark"],
    "actions": ["brushing teeth", "riding a bike", "swimming", "baking a cake", "playing the guitar", "sneezing",
                "walking a dog", "painting a wall", "fishing", "juggling", "sleepwalking", "washing the car",
                "planting a tree", "skiing", "taking a selfie", "mowing the lawn", "knitting", "surfing",
                "climbing a ladder", "making a sandwich"],
    "films": ["The Lion King", "Frozen", "Toy Story", "Finding Nemo", "Shrek", "Harry Potter", "Paddington",
              "Star Wars", "Jaws", "Mary Poppins", "The Jungle Book", "Cinderella", "Peter Pan", "Aladdin",
              "Wallace and Gromit", "Home Alone", "Titanic", "Ghostbusters", "Matilda", "Moana"],
    "jobs": ["teacher", "firefighter", "doctor", "chef", "pilot", "plumber", "farmer", "postman", "dentist",
             "builder", "astronaut", "hairdresser", "police officer", "photographer", "librarian", "window cleaner",
             "vet", "bus driver", "artist", "lifeguard"],
    "food": ["pizza", "spaghetti", "ice cream", "fish and chips", "roast dinner", "sandwich", "pancakes", "popcorn",
             "soup", "banana", "birthday cake", "burger", "sausage roll", "cup of tea", "chocolate", "sushi",
             "toast", "curry", "chips", "watermelon"],
    "objects": ["umbrella", "toothbrush", "telescope", "bicycle", "scissors", "clock", "ladder", "guitar", "kettle",
                "lamp", "pillow", "balloon", "suitcase", "spectacles", "mirror", "candle", "wheelbarrow", "camera",
                "teapot", "trampoline"],
    "sports and hobbies": ["football", "tennis", "golf", "gymnastics", "archery", "cricket", "boxing", "yoga",
                           "fishing", "gardening", "diving", "rowing", "cycling", "ballet", "karate", "chess",
                           "skateboarding", "bowling", "snooker", "camping"],
    "places": ["beach", "castle", "farm", "library", "zoo", "airport", "supermarket", "swimming pool", "circus",
               "lighthouse", "windmill", "police station", "hospital", "playground", "museum", "campsite",
               "railway station", "cinema", "pyramid", "igloo"],
    "tv and books": ["Peppa Pig", "Doctor Who", "The Gruffalo", "Bluey", "Mr Bean", "Strictly Come Dancing",
                     "Alice in Wonderland", "The Very Hungry Caterpillar", "Sherlock Holmes", "Robin Hood",
                     "Winnie the Pooh", "Horrible Histories", "Gladiators", "Love Island", "The Great British Bake Off",
                     "Postman Pat", "Thomas the Tank Engine", "Where's Wally", "Matilda", "The BFG"],
    "easy": ["cat", "dog", "sun", "house", "car", "tree", "fish", "ball", "hat", "cake", "star", "book", "bird",
             "flower", "boat", "shoe", "apple", "moon", "bed", "cup"],
}

DRAWABLE = ["animals", "actions", "films", "jobs", "food", "objects", "sports and hobbies", "places", "easy"]

# Taboo / Articulate style: describe the word without saying it or any of the forbidden words.
TABOO: list[tuple[str, list[str]]] = [
    ("Pizza", ["cheese", "Italy", "slice", "oven", "toppings"]),
    ("Birthday", ["cake", "candles", "party", "present", "age"]),
    ("Football", ["goal", "kick", "pitch", "team", "referee"]),
    ("Elephant", ["trunk", "big", "grey", "Africa", "tusks"]),
    ("Snowman", ["snow", "carrot", "winter", "hat", "build"]),
    ("Rainbow", ["colours", "rain", "sky", "seven", "arch"]),
    ("Library", ["books", "borrow", "quiet", "read", "shelf"]),
    ("Pirate", ["ship", "treasure", "parrot", "sea", "eye patch"]),
    ("Toothbrush", ["teeth", "paste", "mouth", "clean", "bristles"]),
    ("Christmas", ["Santa", "tree", "presents", "December", "reindeer"]),
    ("Umbrella", ["rain", "wet", "hold", "open", "raindrops"]),
    ("Telephone", ["call", "ring", "mobile", "talk", "number"]),
    ("Doctor", ["hospital", "ill", "nurse", "patient", "medicine"]),
    ("Volcano", ["lava", "erupt", "mountain", "hot", "ash"]),
    ("Sandcastle", ["beach", "sand", "bucket", "spade", "build"]),
    ("Butterfly", ["wings", "caterpillar", "fly", "insect", "colourful"]),
    ("Chocolate", ["sweet", "brown", "cocoa", "bar", "melt"]),
    ("Astronaut", ["space", "moon", "rocket", "suit", "NASA"]),
    ("Swimming", ["water", "pool", "stroke", "wet", "float"]),
    ("Guitar", ["strings", "music", "play", "band", "strum"]),
    ("Dentist", ["teeth", "drill", "mouth", "check-up", "tooth"]),
    ("Campfire", ["marshmallow", "wood", "tent", "flames", "burn"]),
    ("Superhero", ["cape", "powers", "save", "mask", "villain"]),
    ("Teapot", ["tea", "pour", "spout", "cup", "brew"]),
    ("Dinosaur", ["extinct", "T-Rex", "fossil", "big", "Jurassic"]),
    ("Scarecrow", ["farm", "field", "birds", "straw", "crops"]),
    ("Rollercoaster", ["fair", "ride", "loop", "fast", "scream"]),
    ("Snowboard", ["snow", "ski", "mountain", "slope", "winter"]),
    ("Fireworks", ["bang", "night", "sky", "rocket", "sparkler"]),
    ("Supermarket", ["shop", "trolley", "food", "buy", "aisle"]),
    ("Bicycle", ["wheels", "pedal", "ride", "helmet", "chain"]),
    ("Lighthouse", ["light", "sea", "ships", "tower", "coast"]),
    ("Pancake", ["flip", "batter", "Shrove Tuesday", "lemon", "pan"]),
    ("Trampoline", ["bounce", "jump", "garden", "springs", "net"]),
    ("Kangaroo", ["Australia", "pouch", "hop", "joey", "jump"]),
    ("Detective", ["crime", "clue", "solve", "Sherlock", "mystery"]),
    ("Wedding", ["bride", "groom", "married", "ring", "cake"]),
    ("Snowflake", ["snow", "cold", "winter", "flake", "ice"]),
    ("Mermaid", ["tail", "sea", "fish", "half", "Ariel"]),
    ("Robot", ["machine", "metal", "artificial", "beep", "control"]),
]

TRUTHS = [
    "What is the silliest thing you have ever been scared of?",
    "What is your favourite family memory?",
    "If you could have any superpower for a day, what would it be?",
    "What is the funniest thing that has ever happened to you at school or work?",
    "What is the best present you have ever been given?",
    "What food could you happily eat every day for a week?",
    "What is your most embarrassing moment that you're happy to share?",
    "Which member of the family is the best cook, and what do they make best?",
    "If you could visit any place in the world, where would you go?",
    "What is the worst joke you know?",
    "What is a talent you have that few people know about?",
    "What is your favourite film to watch when you're feeling down?",
    "Who was your first best friend?",
    "What is the strangest food you have ever tried?",
    "If you were invisible for an hour, what would you do?",
    "What is the most childish thing you still enjoy?",
    "What song do you secretly love singing along to?",
    "What is the nicest thing someone has done for you?",
    "If you had to swap lives with anyone in the room for a day, who would it be?",
    "What was your favourite toy when you were little?",
    "What is the funniest nickname you have ever had?",
    "What is one thing you would change about your bedroom?",
    "What would your perfect birthday look like?",
    "What is the silliest thing you have ever cried about?",
    "What job did you want to do when you were five?",
    "What is the most boring thing you have ever done and enjoyed?",
    "What animal do you think you are most like, and why?",
    "What is your favourite thing about the person on your left?",
    "What is the longest you have ever stayed awake?",
    "What would you do with a million pounds?",
    "Which fictional character would you most like to have dinner with?",
    "What is the worst present you have ever received, and how did you react?",
    "What is the bravest thing you have ever done?",
    "What is your favourite thing to do on a rainy day?",
    "If you could be famous for one thing, what would it be?",
]

DARES = [
    "Speak in a robot voice until your next turn.",
    "Do your best impression of a chicken for ten seconds.",
    "Sing the first verse of a song of the group's choice.",
    "Walk across the room like a penguin.",
    "Say the alphabet backwards as far as you can.",
    "Tell a joke, and keep a straight face while you do it.",
    "Do ten star jumps.",
    "Talk in a silly accent for the next two minutes.",
    "Balance a spoon on your nose for as long as you can.",
    "Pretend to be a news reporter and report on what is happening in the room.",
    "Dance with no music for 20 seconds.",
    "Draw a picture of the person on your right with your eyes closed.",
    "Do your best superhero pose and give yourself a hero name.",
    "Let the group choose a funny voice for you to use for your next three sentences.",
    "Try to lick your elbow.",
    "Hop on one foot while counting to twenty.",
    "Make up a two-line poem about the person on your left.",
    "Do an impression of a famous person and let the group guess who it is.",
    "Say 'red lorry, yellow lorry' five times fast.",
    "Act out your favourite animal until someone guesses it.",
    "Give everyone in the room a compliment.",
    "Pretend to be a waiter and take a drinks order from everyone.",
    "Build the tallest tower you can from things on the table in one minute.",
    "Sing 'Happy Birthday' in your best opera voice.",
    "Try to tell a story using only questions.",
    "Do the worm, or the closest thing to it you can manage.",
    "Talk without closing your mouth for 30 seconds.",
    "Mime brushing your teeth in slow motion.",
    "Wear a sock as a glove for the next three rounds.",
    "Say something nice about each person in the room in one breath.",
    "Do a silent movie scene for the group to guess.",
    "Make the group laugh without saying a word.",
]

TWO_TRUTHS_PROMPTS = [
    "somewhere you have travelled to", "a food you love or hate", "something you did as a child",
    "a job you have done", "an animal you have met", "a talent or party trick", "something you have won",
    "a famous person you have seen", "a sport you have tried", "something you have broken",
    "a place you have lived", "something you can cook", "an accident or mishap", "a book, film or song you love",
    "something you are scared of", "a language or a few words you know", "something you collect",
    "a strange thing you own",
]

ICEBREAKERS = [
    "If you could only eat one food for the rest of your life, what would it be?",
    "What is your favourite board game or card game?",
    "What was the first concert or show you went to?",
    "If you could time travel, would you go to the past or the future?",
    "What is your go-to karaoke song?",
    "Would you rather fly or be invisible?",
    "What is the best holiday you have ever had?",
    "What is your favourite biscuit?",
    "Which three things would you take to a desert island?",
    "What is the best piece of advice you have ever been given?",
    "What is your favourite season and why?",
    "What was your favourite TV show as a child?",
    "If you could have dinner with anyone, living or dead, who would it be?",
    "What is something you are looking forward to?",
    "What is the funniest thing you have seen this week?",
    "What is your favourite smell?",
    "What was your first job?",
    "If you could instantly learn any skill, what would it be?",
    "What is the best meal you have ever eaten?",
    "Which fictional world would you most like to live in?",
    "Tea or coffee, and how do you take it?",
    "What is the most useless talent you have?",
    "What is your favourite dessert?",
    "If you won the lottery tomorrow, what is the first thing you would buy?",
    "What is your favourite thing about where you live?",
]

SCATTER_CATEGORIES = [
    "A girl's name", "A boy's name", "An animal", "A country", "A city or town", "A food", "A drink",
    "Something you find in a kitchen", "A job", "A fruit or vegetable", "A film title", "A sport or game",
    "Something you wear", "A colour", "A famous person", "Something found at the seaside", "A musical instrument",
    "A TV show", "Something you find in a bathroom", "A car brand", "A type of weather", "A hobby",
    "Something round", "Something you take on holiday", "A book title", "A boy's or girl's toy",
    "Something you find in a garden", "A song title", "A sweet or chocolate bar", "Something cold",
    "A reason to be late", "A body part", "A type of transport", "A river or sea", "A tool",
]
SCATTER_LETTERS = "ABCDEFGHIJKLMNOPRSTW"
