"""Built-in tables for pets and the garden (UK): toxic foods, first aid, breeds, sowing, plant care, jobs by month.

General guidance only. For a poisoned or injured pet, phone a vet straight away.
"""

MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October",
          "November", "December"]

# ---- Pets ---------------------------------------------------------------------------------------------------

# food: (dogs, cats, why). Levels: toxic, caution, ok.
TOXIC = {
    "chocolate": ("toxic", "toxic", "Theobromine; dark and baking chocolate are the worst."),
    "grapes": ("toxic", "toxic", "Can cause kidney failure, even in small amounts."),
    "raisins": ("toxic", "toxic", "Dried grapes, including sultanas and currants, can cause kidney failure."),
    "onion": ("toxic", "toxic", "Damages red blood cells; cooked or raw, and onion powder."),
    "garlic": ("toxic", "toxic", "Damages red blood cells; stronger than onion."),
    "chives": ("toxic", "toxic", "Part of the onion family."),
    "leeks": ("toxic", "toxic", "Part of the onion family."),
    "xylitol": ("toxic", "toxic", "Sweetener in sugar-free gum, some peanut butters and sweets; very dangerous."),
    "macadamia nuts": ("toxic", "caution", "Weakness, tremors and vomiting in dogs."),
    "alcohol": ("toxic", "toxic", "Even small amounts are dangerous."),
    "coffee": ("toxic", "toxic", "Caffeine; also tea and energy drinks."),
    "tea": ("toxic", "toxic", "Caffeine."),
    "avocado": ("caution", "caution", "Persin can upset stomachs; the stone is a choking risk."),
    "cooked bones": ("toxic", "toxic", "They splinter and can pierce the gut or cause choking."),
    "raw dough": ("toxic", "toxic", "Yeast expands in the stomach and makes alcohol."),
    "nutmeg": ("toxic", "toxic", "Causes tremors and an upset stomach."),
    "corn on the cob": ("caution", "caution", "The cob can block the gut; sweetcorn kernels alone are fine."),
    "cherries": ("caution", "caution", "Stones and stems contain cyanide; the flesh is fine."),
    "peach stones": ("toxic", "toxic", "Pits contain cyanide and can block the gut."),
    "tomato leaves": ("caution", "caution", "Green parts are mildly toxic; ripe tomato is fine in small amounts."),
    "rhubarb": ("toxic", "toxic", "Leaves have oxalates that harm kidneys."),
    "milk": ("caution", "caution", "Many are lactose intolerant; it can cause an upset tummy."),
    "cheese": ("caution", "caution", "Rich and salty; small pieces occasionally, and never blue cheese."),
    "salt": ("caution", "caution", "Too much causes salt poisoning; avoid salty snacks."),
    "fatty food": ("caution", "caution", "Trimmings and fried food can cause pancreatitis."),
    "raw fish": ("caution", "caution", "Parasites; raw fish also breaks down vitamin B1 in cats."),
    "tuna": ("ok", "caution", "Fine for dogs as a treat; too much for cats can cause mercury and nutrition problems."),
    "liver": ("caution", "caution", "Small amounts are fine; too much vitamin A is harmful."),
    "lilies": ("caution", "toxic", "Every part of a lily, even pollen or vase water, can kill a cat."),
    "apple": ("ok", "ok", "Fine without the core and pips."),
    "banana": ("ok", "ok", "Fine in small pieces as a treat."),
    "blueberries": ("ok", "ok", "A safe, healthy treat."),
    "carrot": ("ok", "ok", "A safe crunchy treat, cooked or raw for dogs."),
    "cucumber": ("ok", "ok", "Safe and low in calories."),
    "plain chicken": ("ok", "ok", "Cooked, boneless and unseasoned is fine."),
    "peanut butter": ("caution", "caution", "Fine for dogs only if it has no xylitol; check the label."),
    "watermelon": ("ok", "ok", "Fine without seeds or rind."),
    "eggs": ("ok", "ok", "Fully cooked is fine."),
    "rice": ("ok", "ok", "Plain and cooked is fine and good for upset tummies."),
    "pumpkin": ("ok", "ok", "Plain cooked pumpkin is fine."),
    "mushrooms": ("caution", "caution", "Shop mushrooms are low risk but wild ones can be deadly; avoid."),
    "ice cream": ("caution", "caution", "Sugar and dairy; some contain xylitol or chocolate."),
    "bread": ("ok", "ok", "A little plain bread is fine; never raw dough or raisin bread."),
}

FIRST_AID_KIT = ["Vet's phone number and out-of-hours number", "Pet insurance details",
                 "Sterile saline for washing eyes and wounds", "Non-stick sterile dressings and bandage",
                 "Self-adhesive bandage (no elastic bands)", "Blunt-ended scissors",
                 "Tweezers or a tick remover", "Digital thermometer (a pet's normal is 38 to 39 C)",
                 "Disposable gloves", "Muzzle or soft cloth (even gentle pets bite when hurt)",
                 "Towel or blanket", "Antiseptic wash made for pets", "Recent photo and weight of your pet",
                 "Spare lead and carrier"]

FIRST_AID = {
    "bleeding": "Press a clean pad firmly on the wound and keep pressing. Don't remove soaked pads; add more on top. "
                "Bandage lightly and get to a vet.",
    "choking": "If they can breathe, keep calm and get to a vet. If they can't, look in the mouth and remove anything "
               "you can see safely. Don't push blindly. Phone the vet while you go.",
    "heatstroke": "Move to shade, wet them with cool (not ice) water, offer small sips, and get to a vet at once. "
                  "Never leave a pet in a car.",
    "poisoning": "Take away what they ate, keep the packet, don't make them sick unless a vet says to. "
                 "Phone your vet straight away.",
    "stings": "Scrape a bee sting out sideways. Cold compress. Watch for a swollen face or trouble breathing, which "
              "means the vet now.",
    "seizure": "Stay calm, move things away, don't touch their mouth, dim the lights and time it. Over 3 minutes, or "
               "several in a row, is an emergency.",
    "burns": "Cool with running cool water for 10 minutes, cover with a clean damp cloth, and see a vet.",
    "broken bone": "Keep them still and warm, don't try to set it, support gently on a board or blanket and go to a vet.",
    "snake bite": "Keep them calm and still, don't cut or suck the wound, and get to a vet quickly. "
                  "Adders are the UK's only venomous snake.",
}

# breed: (size, weight, life span, exercise, note)
BREEDS = {
    "labrador": ("large", "25 to 36 kg", "10 to 12 years", "1 to 2 hours a day", "Friendly, loves food and water; watch the weight."),
    "golden retriever": ("large", "25 to 34 kg", "10 to 12 years", "1 to 2 hours a day", "Gentle and eager; sheds a lot."),
    "german shepherd": ("large", "22 to 40 kg", "9 to 13 years", "2 hours a day", "Clever working dog that needs a job."),
    "cocker spaniel": ("medium", "12 to 16 kg", "12 to 15 years", "1 to 1.5 hours a day", "Merry and busy; ears need regular cleaning."),
    "springer spaniel": ("medium", "18 to 25 kg", "12 to 14 years", "2 hours a day", "Very energetic; happiest with lots to do."),
    "border collie": ("medium", "12 to 20 kg", "12 to 15 years", "2 hours plus", "Extremely clever; needs mental work as well as walks."),
    "french bulldog": ("small", "8 to 14 kg", "10 to 12 years", "30 to 60 minutes", "Flat face means they overheat easily."),
    "pug": ("small", "6 to 9 kg", "12 to 15 years", "30 to 60 minutes", "Flat face; keep cool and slim."),
    "dachshund": ("small", "7 to 15 kg", "12 to 16 years", "up to 1 hour", "Long back; avoid stairs and jumping."),
    "beagle": ("medium", "9 to 11 kg", "12 to 15 years", "1 hour plus", "Follows its nose; keep on a lead near wildlife."),
    "staffordshire bull terrier": ("medium", "11 to 17 kg", "12 to 14 years", "1 hour", "Loyal and people-loving."),
    "poodle": ("medium", "7 to 27 kg", "12 to 15 years", "1 hour", "Clever, low shedding; needs regular grooming."),
    "chihuahua": ("small", "1.5 to 3 kg", "14 to 16 years", "30 minutes", "Tiny and bold; feels the cold."),
    "jack russell": ("small", "5 to 8 kg", "13 to 16 years", "1 hour", "Fearless and busy; needs lots to do."),
    "husky": ("large", "16 to 27 kg", "12 to 14 years", "2 hours plus", "Loves to run and howl; a great escape artist."),
    "boxer": ("large", "25 to 32 kg", "10 to 12 years", "1 to 2 hours", "Playful and stays puppyish for years."),
    "rottweiler": ("large", "35 to 60 kg", "8 to 10 years", "1 to 2 hours", "Loyal and strong; needs good training."),
    "shih tzu": ("small", "4 to 7 kg", "10 to 16 years", "30 minutes", "Affectionate lapdog; the coat needs daily brushing."),
    "cavalier king charles spaniel": ("small", "5 to 8 kg", "9 to 14 years", "1 hour", "Gentle; prone to heart problems, so choose a checked breeder."),
    "whippet": ("medium", "9 to 19 kg", "12 to 15 years", "1 hour", "Quiet indoors, fast outdoors."),
}
BREED_WORDS = {"lab": "labrador", "golden": "golden retriever", "gsd": "german shepherd", "alsatian": "german shepherd",
               "cocker": "cocker spaniel", "springer": "springer spaniel", "collie": "border collie",
               "frenchie": "french bulldog", "staffy": "staffordshire bull terrier",
               "staffie": "staffordshire bull terrier", "staffordshire": "staffordshire bull terrier",
               "jrt": "jack russell", "siberian husky": "husky", "cavalier": "cavalier king charles spaniel",
               "sausage dog": "dachshund"}
# dog.ceo names its breeds as breed or breed/sub-breed.
DOG_CEO = {"golden retriever": "retriever/golden", "cocker spaniel": "spaniel/cocker", "springer spaniel": "spaniel/springer",
           "german shepherd": "germanshepherd", "border collie": "collie/border", "french bulldog": "bulldog/french",
           "staffordshire bull terrier": "terrier/staffordshire", "jack russell": "terrier/russell",
           "cavalier king charles spaniel": "spaniel/blenheim", "shih tzu": "shihtzu", "poodle": "poodle/standard"}

# ---- Garden -------------------------------------------------------------------------------------------------

# crop: (kind, sow under cover, sow outdoors, plant out, harvest, tip). Months are 1 to 12 tuples.
SOW = {
    "broad beans": ("veg", (2, 3), (3, 4, 10, 11), (4, 5), (6, 7), "Pinch out the tops once pods form to deter blackfly."),
    "peas": ("veg", (3,), (3, 4, 5, 6), (5,), (6, 7, 8), "Give twiggy sticks or netting to climb."),
    "runner beans": ("veg", (4, 5), (5, 6), (6,), (7, 8, 9), "Wait until frost has passed; pick often for more pods."),
    "french beans": ("veg", (4, 5), (5, 6), (6,), (7, 8, 9), "Dwarf types need no support."),
    "carrots": ("veg", (), (3, 4, 5, 6, 7), (), (6, 7, 8, 9, 10), "Sow thinly in stone-free soil; cover to keep carrot fly out."),
    "beetroot": ("veg", (3,), (4, 5, 6, 7), (), (6, 7, 8, 9, 10), "Each 'seed' is a cluster, so thin the seedlings."),
    "parsnips": ("veg", (), (3, 4, 5), (), (10, 11, 12, 1, 2), "Slow to germinate; use fresh seed every year."),
    "potatoes": ("veg", (), (3, 4), (), (6, 7, 8, 9), "Chit seed potatoes first; earth up shoots to avoid greening."),
    "onions": ("veg", (), (3, 4), (), (7, 8), "Sets are easier than seed; lift when the tops fall over."),
    "garlic": ("veg", (), (10, 11, 2), (), (7, 8), "Plant cloves in autumn for the biggest bulbs."),
    "leeks": ("veg", (3, 4), (), (6, 7), (10, 11, 12, 1, 2), "Drop each seedling into a deep dibbed hole."),
    "lettuce": ("veg", (2, 3), (4, 5, 6, 7, 8), (4, 5), (5, 6, 7, 8, 9, 10), "Sow a few every fortnight so it isn't all ready at once."),
    "spinach": ("veg", (), (3, 4, 8, 9), (), (5, 6, 9, 10, 11), "Bolts in heat; sow in cooler months."),
    "rocket": ("veg", (), (3, 4, 5, 6, 7, 8, 9), (), (5, 6, 7, 8, 9, 10), "Fast and easy; keep watered."),
    "radish": ("veg", (), (3, 4, 5, 6, 7, 8, 9), (), (4, 5, 6, 7, 8, 9, 10), "Ready in about four weeks; ideal for kids."),
    "tomatoes": ("veg", (2, 3, 4), (), (5, 6), (7, 8, 9, 10), "Feed weekly with tomato feed once flowering."),
    "cucumbers": ("veg", (4, 5), (), (5, 6), (7, 8, 9), "Greenhouse types like heat; ridge types can grow outside."),
    "courgettes": ("veg", (4, 5), (5, 6), (5, 6), (7, 8, 9, 10), "Pick small and often."),
    "squash and pumpkins": ("veg", (4, 5), (5, 6), (6,), (9, 10), "Give plenty of space and feed."),
    "sweetcorn": ("veg", (4, 5), (5, 6), (6,), (8, 9), "Plant in blocks, not rows, for pollination."),
    "kale": ("veg", (4, 5), (5, 6), (6, 7), (10, 11, 12, 1, 2, 3), "Net against pigeons and cabbage whites."),
    "cabbage": ("veg", (3, 4), (4, 5), (5, 6), (8, 9, 10, 11), "Firm the soil well around each plant."),
    "brussels sprouts": ("veg", (3, 4), (4,), (5, 6), (10, 11, 12, 1, 2), "Stake tall plants against wind."),
    "cauliflower": ("veg", (3, 4), (4, 5), (5, 6), (8, 9, 10, 11), "Needs steady watering."),
    "broccoli": ("veg", (3, 4), (4, 5), (5, 6), (7, 8, 9, 10, 11), "Net against pigeons."),
    "spring onions": ("veg", (), (3, 4, 5, 6, 7, 8), (), (5, 6, 7, 8, 9, 10), "Sow little and often."),
    "chard": ("veg", (), (4, 5, 6, 7), (), (6, 7, 8, 9, 10, 11), "Cut and come again."),
    "turnips": ("veg", (), (3, 4, 5, 6, 7, 8), (), (5, 6, 7, 8, 9, 10, 11), "Pick when small for the best taste."),
    "strawberries": ("veg", (), (), (3, 4, 8, 9), (6, 7, 8), "Plant runners in late summer for fruit next year."),
    "basil": ("herb", (4, 5), (), (6,), (6, 7, 8, 9), "Likes warmth; pinch out flower buds."),
    "parsley": ("herb", (3, 4), (4, 5, 6, 7), (5, 6), (5, 6, 7, 8, 9, 10), "Slow to germinate; soak seed overnight."),
    "coriander": ("herb", (), (4, 5, 6, 7, 8), (), (6, 7, 8, 9), "Sow often; it bolts quickly."),
    "chives": ("herb", (3, 4), (4, 5), (5, 6), (4, 5, 6, 7, 8, 9), "Perennial; cut hard and it regrows."),
    "dill": ("herb", (), (4, 5, 6, 7), (), (6, 7, 8, 9), "Doesn't like being moved; sow where it will grow."),
    "mint": ("herb", (), (), (4, 5, 9), (5, 6, 7, 8, 9), "Grow in a pot or it will take over the bed."),
    "thyme": ("herb", (3, 4), (5,), (5, 6), (5, 6, 7, 8, 9), "Prefers dry, sunny, poor soil."),
    "rosemary": ("herb", (), (), (4, 5, 9), (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), "Buy a plant; hates wet winters."),
    "sage": ("herb", (3, 4), (5,), (5, 6), (4, 5, 6, 7, 8, 9, 10), "Evergreen and hardy; trim after flowering."),
    "sweet peas": ("flower", (10, 11, 2, 3), (4,), (4, 5), (6, 7, 8), "Pick often to keep them flowering."),
    "sunflowers": ("flower", (4,), (5,), (5, 6), (7, 8, 9), "Protect young plants from slugs."),
    "nasturtiums": ("flower", (4,), (5, 6), (5, 6), (6, 7, 8, 9), "Edible flowers and leaves; easy for children."),
    "marigolds": ("flower", (3, 4), (5,), (5, 6), (6, 7, 8, 9, 10), "Great next to tomatoes."),
    "cosmos": ("flower", (3, 4), (5,), (5, 6), (7, 8, 9, 10), "Good cut flowers; deadhead often."),
    "sweet william": ("flower", (), (5, 6), (9, 10), (5, 6), "A biennial: sow this year, flowers next."),
    "foxgloves": ("flower", (), (5, 6, 7), (9, 10), (6, 7), "Biennial; loved by bees; all parts are poisonous."),
    "wallflowers": ("flower", (), (5, 6), (10, 11), (3, 4, 5), "Sow early summer for spring flowers."),
    "poppies": ("flower", (), (3, 4, 9), (), (6, 7, 8), "Scatter and barely cover."),
    "forget-me-nots": ("flower", (), (5, 6, 7), (9, 10), (4, 5), "Self-seeds happily."),
    "daffodils": ("flower", (), (), (9, 10), (3, 4), "Plant bulbs pointy end up, about 3 times their depth."),
    "tulips": ("flower", (), (), (10, 11), (4, 5), "Plant in October and November to avoid tulip fire."),
    "lavender": ("flower", (), (), (4, 5, 9), (6, 7, 8), "Sunny, well-drained spot; trim after flowering."),
}

JOBS = {
    1: ["Order seeds and seed potatoes", "Prune apple and pear trees while dormant", "Clean pots, trays and tools",
        "Feed the birds and break ice on ponds", "Chit early potatoes indoors"],
    2: ["Sow tomatoes, chillies and sweet peas under cover", "Prune winter-flowering shrubs and clematis",
        "Cut back last year's grasses and perennials", "Chit potatoes", "Fork over empty beds"],
    3: ["Sow hardy veg outdoors when soil warms", "Plant onion sets and early potatoes",
        "Mow for the first time and edge the lawn", "Divide perennials", "Watch for late frosts and keep fleece handy"],
    4: ["Sow beans, courgettes and squash under cover", "Plant out potatoes and shallots",
        "Feed the lawn and rake out moss", "Set up plant supports", "Slug patrol on new growth"],
    5: ["Harden off tender plants before planting out", "Plant out after the last frost", "Water new plantings well",
        "Keep on top of weeds", "Plant up hanging baskets"],
    6: ["Water in the morning or evening", "Feed tomatoes weekly", "Deadhead flowers to keep them blooming",
        "Pick peas, salads and strawberries", "Tie in climbers"],
    7: ["Water containers daily in hot spells", "Summer-prune wisteria", "Pick courgettes and beans often",
        "Sow winter veg like kale and cabbages", "Take cuttings of pelargoniums and herbs"],
    8: ["Harvest onions and potatoes, dry them well", "Sow spring cabbage and salad leaves",
        "Trim hedges after nesting is over", "Collect seed from flowers", "Order spring bulbs"],
    9: ["Plant spring bulbs", "Sow lawn seed or repair patches", "Take in tender plants before frost",
        "Start a compost heap with fallen leaves", "Plant garlic and autumn onions"],
    10: ["Rake leaves off the lawn and beds", "Plant tulips and garlic", "Cut back perennials that have died down",
         "Clean the greenhouse", "Mulch beds with compost"],
    11: ["Plant bare-root trees and roses", "Protect tender plants with fleece", "Clean and store tools",
         "Make leaf mould", "Last mow of the year on a high setting"],
    12: ["Check stored fruit and veg", "Protect pots from frost", "Prune vines and old apple trees",
         "Order seed catalogues", "Feed the birds and keep water unfrozen"],
}

LAWN = {
    1: "Keep off frosty grass. Clean and service the mower.",
    2: "Keep off wet or frozen grass. Order seed and feed.",
    3: "First cut on a high setting, and only when dry. Edge the borders.",
    4: "Feed with a spring lawn feed, rake out moss and sow bare patches.",
    5: "Mow weekly. Treat weeds if needed. Lower the blades gradually.",
    6: "Mow weekly, leave short clippings on. Water new turf; don't cut too short in heat.",
    7: "Raise the blade and mow less in drought. Grass browns but recovers.",
    8: "Don't feed in drought. Water new lawns, mow high.",
    9: "Best month: scarify, aerate and overseed, then use an autumn feed.",
    10: "Rake up leaves, keep mowing but higher. Last chance to overseed.",
    11: "Last cut of the year. Clear leaves; stay off frosty grass.",
    12: "Do nothing but stay off frozen or waterlogged lawn.",
}

COMPANIONS = {
    "tomatoes": (["basil", "marigolds", "carrots", "parsley", "onions"], ["potatoes", "fennel", "brassicas"]),
    "carrots": (["onions", "leeks", "chives", "rosemary", "lettuce"], ["dill", "parsnips"]),
    "onions": (["carrots", "beetroot", "lettuce", "strawberries"], ["peas", "beans"]),
    "beans": (["carrots", "sweetcorn", "cucumbers", "marigolds", "potatoes"], ["onions", "garlic", "fennel"]),
    "peas": (["carrots", "radish", "lettuce", "cucumbers", "turnips"], ["onions", "garlic", "chives"]),
    "potatoes": (["beans", "sweetcorn", "cabbage", "marigolds"], ["tomatoes", "cucumbers", "squash"]),
    "cabbage": (["onions", "dill", "chamomile", "nasturtiums", "beetroot"], ["strawberries", "tomatoes"]),
    "lettuce": (["carrots", "radish", "strawberries", "cucumbers", "chives"], ["parsley", "celery"]),
    "courgettes": (["nasturtiums", "sweetcorn", "beans", "marigolds"], ["potatoes"]),
    "cucumbers": (["beans", "peas", "sweetcorn", "nasturtiums", "dill"], ["potatoes", "sage"]),
    "sweetcorn": (["beans", "squash", "cucumbers", "peas"], ["tomatoes"]),
    "strawberries": (["borage", "chives", "lettuce", "spinach", "thyme"], ["cabbage", "fennel"]),
    "beetroot": (["onions", "lettuce", "cabbage", "garlic"], ["runner beans"]),
    "garlic": (["roses", "tomatoes", "carrots", "beetroot"], ["peas", "beans"]),
    "leeks": (["carrots", "celery", "onions"], ["beans", "peas"]),
    "radish": (["carrots", "lettuce", "peas", "cucumbers"], ["hyssop"]),
    "basil": (["tomatoes", "peppers"], ["rue"]),
    "parsley": (["tomatoes", "asparagus", "carrots"], ["lettuce"]),
    "roses": (["garlic", "chives", "lavender", "marigolds"], ["other roses planted too close"]),
    "spinach": (["strawberries", "peas", "beans", "radish"], ["potatoes"]),
}

COMPOST_GOOD = {
    "Greens (wet, nitrogen)": ["Vegetable and fruit peelings", "Tea bags (plastic-free) and coffee grounds",
                               "Grass clippings in thin layers", "Weeds without seeds or roots", "Plant trimmings",
                               "Crushed egg shells"],
    "Browns (dry, carbon)": ["Cardboard and scrunched paper", "Autumn leaves", "Straw and hay",
                             "Woody prunings chopped small", "Egg boxes", "A little untreated sawdust"],
}
COMPOST_BAD = ["Meat, fish and bones (rats and smells)", "Cooked food and leftovers", "Dairy and oil", "Cat and dog mess",
               "Diseased plants (blight, club root)", "Perennial weed roots (bindweed, ground elder) and weeds in seed",
               "Coal ash and barbecue charcoal", "Glossy magazines and treated wood", "Nappies"]
COMPOST_TIPS = ["Mix roughly equal amounts of greens and browns.", "Keep it damp, like a wrung-out sponge.",
                "Turn every few weeks to add air.", "Ready in 6 to 12 months when dark and crumbly.",
                "Cover to keep the heat in and rain out."]

# plant: (kind, water, light, feed, tip)
PLANTS = {
    "monstera": ("house", "When the top 5 cm is dry, about weekly", "Bright, indirect", "Monthly in spring and summer", "Wipe the leaves; give it a moss pole."),
    "spider plant": ("house", "Weekly; likes to stay slightly damp", "Bright to medium, indirect", "Monthly in summer", "Brown tips mean tap water minerals; use rainwater."),
    "peace lily": ("house", "When it droops, or weekly", "Shade to medium", "Every 6 weeks in growth", "Droops dramatically when thirsty and bounces back."),
    "snake plant": ("house", "Every 2 to 3 weeks; let it dry out", "Almost anywhere", "Twice a year", "Very hard to kill; overwatering is the danger."),
    "pothos": ("house", "When the top 3 cm is dry", "Low to bright, indirect", "Monthly in summer", "Trails beautifully; trim to make it bushy."),
    "rubber plant": ("house", "When the top is dry, every 1 to 2 weeks", "Bright, indirect", "Monthly in summer", "Dust the big leaves."),
    "fiddle leaf fig": ("house", "Weekly when the top 5 cm is dry", "Bright, no direct sun", "Fortnightly in summer", "Doesn't like being moved."),
    "aloe vera": ("house", "Every 2 to 3 weeks, drench then dry", "Bright, some sun", "Twice in summer", "Use gritty compost."),
    "cactus": ("house", "Monthly in summer, hardly at all in winter", "Full sun", "Twice in summer", "A winter rest keeps it healthy."),
    "orchid": ("house", "Weekly soak, then drain", "Bright, no hot sun", "Every 2 weeks with orchid food", "Water from the bottom; don't leave it in water."),
    "boston fern": ("house", "Keep the soil damp", "Medium, indirect", "Monthly in summer", "Loves humidity; good in a bathroom."),
    "african violet": ("house", "Water from below when the top is dry", "Bright, indirect", "Fortnightly with violet feed", "Keep water off the leaves."),
    "christmas cactus": ("house", "When the top is dry; less in autumn", "Bright, indirect", "Monthly in spring and summer", "Cool dark nights trigger flowers."),
    "jade plant": ("house", "Every 2 to 3 weeks", "Bright, sunny", "Twice in summer", "Wrinkled leaves mean it is thirsty."),
    "zz plant": ("house", "Every 2 to 3 weeks", "Low to bright", "Twice in summer", "Stores water in its roots."),
    "chinese money plant": ("house", "When the top 3 cm is dry", "Bright, indirect", "Monthly in summer", "Turn regularly so it grows evenly."),
    "basil (pot)": ("house", "Keep moist, morning is best", "Sunniest windowsill", "Fortnightly", "Pinch out flower buds."),
    "lavender": ("garden", "Once established, rarely", "Full sun", "Not needed; a little potash", "Trim after flowering; don't cut into old wood."),
    "roses": ("garden", "Deep water weekly in dry spells", "Full sun", "Rose feed in spring and after first flush", "Prune in late winter."),
    "hydrangea": ("garden", "Plenty; likes moist soil", "Sun to part shade", "Spring feed", "Blue or pink depends on soil acidity."),
    "geraniums": ("garden", "When the top is dry", "Full sun", "Weekly tomato feed in summer", "Bring inside before frost."),
    "fuchsia": ("garden", "Keep moist", "Part shade", "Fortnightly in summer", "Hardy types are worth leaving in the ground."),
    "clematis": ("garden", "Deep water in dry spells", "Sun on top, shade at the feet", "Spring feed", "Pruning group depends on the variety."),
    "tomatoes": ("garden", "Daily in hot weather, at the roots", "Full sun", "Weekly tomato feed when flowering", "Pinch out side shoots on cordon types."),
    "strawberries": ("garden", "Regularly when fruiting", "Full sun", "Tomato feed when flowering", "Straw under the fruit keeps it clean."),
    "hostas": ("garden", "Keep moist", "Shade", "Spring mulch", "Slugs love them; use traps rather than pellets around pets."),
    "sweet peas": ("garden", "Regularly; don't let them dry out", "Full sun", "Fortnightly high-potash feed", "Pick often."),
    "rhubarb": ("garden", "Keep moist in dry spells", "Sun or part shade", "Mulch in spring", "Don't pull stalks in the first year."),
    "herbs (thyme, rosemary)": ("garden", "Sparingly", "Full sun", "Hardly at all", "Grit in the soil helps drainage."),
    "dahlias": ("garden", "Deep water twice a week in dry spells", "Full sun", "Fortnightly high-potash feed", "Lift tubers before hard frost or mulch thickly."),
    "hanging baskets": ("garden", "Daily in summer", "Sun or part shade", "Weekly feed from June", "Deadhead to keep flowering."),
}
