"""Built-in tables for the nature abilities: common UK birds and trees for ID hints, and what's in season by month.

Look-and-feel words in the "look" strings are what a description gets matched against, so keep them plain.
"""

# name: (size, look, where and when, fact and what it eats)
BIRDS = {
    "Robin": ("small", "round brown back, orange-red face and breast, dark eyes, upright stance, tame",
              "gardens all year; sings even in winter and at night near street lights",
              "Territorial and bold, it follows gardeners for worms. Likes mealworms, suet and fat."),
    "Blue tit": ("tiny", "bright blue cap, wings and tail, yellow belly, white cheeks, dark eye stripe",
                 "gardens and woods all year, hangs upside down on feeders", "Nests in boxes. Likes peanuts, sunflower hearts and fat balls."),
    "Great tit": ("small", "black head, white cheeks, yellow belly with a black stripe down the middle, green back",
                  "gardens and woods all year", "Loud two-note 'teacher, teacher' song. Likes sunflower seeds and peanuts."),
    "Coal tit": ("tiny", "black cap, white patch on the back of the neck, grey back, buff belly, small",
                 "gardens near conifers all year", "Snatches a seed and hides it to eat later. Likes sunflower hearts and peanuts."),
    "Long-tailed tit": ("tiny", "round pink, black and white ball with a very long tail, fluffy, flocks",
                        "hedges and gardens, in small chattering groups, mostly winter", "Builds a domed nest of moss and spiders' webs. Likes fat balls and suet."),
    "Blackbird": ("medium", "male all black with a bright orange-yellow beak and eye ring; female dark brown, streaky breast",
                  "lawns and hedges all year, hops and tugs worms", "Sings a rich, flute-like song at dusk. Likes worms, berries, apples and mealworms."),
    "Song thrush": ("medium", "warm brown back, cream belly with dark speckles, speckled breast",
                    "gardens and hedges, sings the same phrases two or three times", "Smashes snail shells on a favourite stone. Likes snails, worms and berries."),
    "Mistle thrush": ("large", "grey-brown back, large round spots on a white belly, big, upright, white outer tail",
                      "fields, parks and tall trees; sings in wind and rain", "Defends a berry tree fiercely in winter. Likes berries, worms and insects."),
    "Redwing": ("medium", "brown back, creamy stripe above the eye, red-orange flanks under the wing, speckled",
                "winter visitor to fields and berry bushes, often in flocks", "Arrives from Scandinavia in October. Eats berries and worms."),
    "Fieldfare": ("large", "grey head and rump, chestnut back, speckled orange-yellow breast, big thrush, flocks",
                  "winter visitor to fields, hedges and orchards", "Arrives in autumn and strips hawthorn berries. Loves apples left on the ground."),
    "Dunnock": ("small", "brown streaky back, grey head and breast, thin beak, shuffling, quiet, dull",
                "under hedges and shrubs all year, shuffles on the ground", "Sometimes called the hedge sparrow, but is not a sparrow. Eats insects and small seeds."),
    "House sparrow": ("small", "male grey crown, brown back, black bib; female plain brown, streaked, chirpy, noisy",
                      "chattering flocks around houses all year, take dust baths", "Declining in the UK. Likes seed mixes, sunflower hearts and dense hedges to roost in."),
    "Starling": ("medium", "glossy black with purple and green sheen, speckled in winter, yellow beak, strut, noisy",
                 "roofs, aerials and lawns, huge flocks at dusk", "A great mimic; huge evening murmurations. Likes suet, mealworms and insects."),
    "Chaffinch": ("small", "pinkish breast, blue-grey cap, two white wing bars, female brown-grey",
                  "gardens and woods, feeds on the ground under feeders", "Song is a rattling, falling trill. Eats seeds and insects."),
    "Goldfinch": ("small", "red face, black and white head, gold and black wings, tinkling song, flocks",
                  "gardens and thistle fields, hangs on seed heads and feeders", "Loves nyjer seed and teasel. Its flock is called a charm."),
    "Greenfinch": ("small", "olive-green, yellow flashes on wings and tail, thick pale beak, wheezing call",
                   "gardens and hedges", "Declined because of a disease; keep feeders clean. Likes sunflower hearts."),
    "Bullfinch": ("small", "bright pink-red breast, black cap, blue-grey back, white rump, thick beak, shy",
                  "hedges and woods, usually in pairs, soft piping call", "Eats buds and seeds. Look for the white rump as it flies away."),
    "Siskin": ("tiny", "small yellow-green finch, streaky, black chin, black and yellow wings",
               "winter visitor to gardens with peanut feeders and alder trees", "Acrobatic on feeders. Likes nyjer, sunflower hearts and peanuts."),
    "Wood pigeon": ("large", "big grey pigeon with a white neck patch and white wing patch, pink breast, plump",
                    "everywhere, on lawns, roofs and in trees", "Its call sounds like 'my toe hurts, Betty'. Eats seeds, grain, leaves and buds."),
    "Collared dove": ("medium", "pale grey-fawn dove with a thin black collar on the back of the neck, slim",
                      "gardens, roofs and wires; three-note coo", "Arrived in the UK in the 1950s. Eats grain and seed."),
    "Magpie": ("large", "black and white with a long tail that shines blue and green, big",
               "everywhere in gardens and on grass, loud chatter", "Very clever and can recognise itself in a mirror. Eats insects, eggs, scraps and seeds."),
    "Jay": ("medium", "pinkish-brown with a bright blue patch on the wing, black moustache, white rump, shy",
            "woodland edges and gardens with oaks, autumn acorn hoarding", "Buries thousands of acorns and forgets some, planting oaks. Eats acorns and insects."),
    "Jackdaw": ("medium", "small black crow with a grey nape, pale silvery eye, chattering 'jack' call",
                "chimneys, church towers and fields in noisy flocks", "Mates for life. Eats insects, grain and scraps."),
    "Carrion crow": ("large", "all black crow with a strong black beak, alone or in pairs, harsh caw",
                     "fields, streets and parks", "Very clever and can drop nuts on roads for cars to crack. Eats almost anything."),
    "Wren": ("tiny", "tiny round brown bird with a short tail cocked up, loud song, barred wings",
             "hedges and undergrowth, quick and busy", "One of the loudest songs for its size. Eats insects and spiders."),
    "Great spotted woodpecker": ("medium", "black and white with a red patch under the tail, males a red nape, clings to trunks",
                                 "tree trunks and peanut feeders; drums on dead wood in spring", "Wedges nuts in bark and hammers them. Likes peanuts, suet and insects."),
    "Green woodpecker": ("large", "green back, red crown, yellow rump, laughing call, on lawns",
                         "lawns and parkland, looks for ants", "Nicknamed the yaffle for its laugh. Eats ants with a very long tongue."),
    "Nuthatch": ("small", "blue-grey back, buff belly, black eye stripe, walks head-first down tree trunks",
                 "old woods and big garden trees, on feeders", "The only UK bird to climb down trunks headfirst. Likes peanuts and sunflower seeds."),
    "Blackcap": ("small", "grey with a black cap (male) or a rusty-brown cap (female), slim, warbler",
                 "gardens in winter and woods in summer, rich warbling song", "Some spend winter in UK gardens. Likes fat, fruit and berries."),
    "Pied wagtail": ("small", "black, white and grey with a long tail that wags up and down, runs on the ground",
                     "car parks, roofs and lawns, roosts in town centres", "Chases insects at a run. Eats small insects."),
    "Sparrowhawk": ("medium", "small hawk, grey back with barred orange breast, long yellow legs, a quick hunter, yellow eye",
                    "flashes over hedges and gardens looking for small birds", "Ambushes garden birds; a bird of prey, not a problem to worry about."),
    "Tawny owl": ("large", "big round-headed brown owl with dark eyes, mottled, heard at night",
                  "woods and large gardens, the 'twit-twoo' at night", "The female calls 'kewick' and the male 'hoo-hoo'. Eats mice and voles."),
    "Herring gull": ("large", "big grey and white gull with a yellow beak with a red spot, pink legs, noisy",
                     "coast, roofs and chip shops, loud laughing call", "Snatches food from hands. Declining; it is a red-listed bird."),
}

# name: (leaf, other clues, fact)
TREES = {
    "Oak": ("lobed, wavy edges, short stalks, 5 to 7 rounded lobes on each side",
            "acorns in cups, rough deeply grooved bark",
            "Supports more wildlife than any other UK tree, over 2,000 species. Leaves out in April."),
    "Beech": ("oval, smooth, wavy edged with silky hairs when young, pointed tip",
              "smooth grey bark like an elephant's leg, spiky beech nut cases (mast), copper leaves that stay in winter on hedges",
              "Casts deep shade so little grows beneath. Beech leaves are edible when very young."),
    "Ash": ("compound with 9 to 13 leaflets in pairs and one at the end, long, pointed leaflets",
            "black velvety buds, bunches of ash keys (winged seeds), grey furrowed bark",
            "Last to leaf and first to drop; ash dieback is affecting many UK trees."),
    "Sycamore": ("large, five pointed lobes like a hand, palmate, toothed edges, red stalks",
                 "winged seeds like helicopters, bark scaly and pinkish-grey",
                 "Not native but very common. Aphids on it feed many birds and insects."),
    "Field maple": ("small, three to five rounded lobes, palmate, smaller than sycamore",
                    "winged seeds set in a straight line, corky bark, turns gold in autumn",
                    "Britain's only native maple, often found in hedges."),
    "Horse chestnut": ("huge, palmate with five to seven big leaflets like fingers, toothed",
                       "sticky buds, conkers in spiky green cases, candle-like white flowers in May",
                       "Children play conkers with them. Not related to the sweet chestnut and conkers are not edible."),
    "Sweet chestnut": ("long, narrow, glossy, with sharp regular teeth along the edge, oval",
                       "very spiky husk with edible nuts, spiralling ridges on old bark",
                       "Roasted chestnuts at Christmas. The tree was probably brought by the Romans."),
    "Silver birch": ("small, triangular or diamond-shaped, toothed, thin twigs that droop",
                     "white papery bark with black diamonds, catkins in spring",
                     "A pioneer tree, first to grow on bare ground. Leaves are tiny and flutter in the breeze."),
    "Alder": ("round or oval with a notched tip, dark green, toothed, sticky when young",
              "small woody cones like tiny pine cones, near rivers and wet ground",
              "Its roots fix nitrogen. Siskins love its seeds in winter."),
    "Hazel": ("round to heart-shaped, soft and hairy, toothed, pointed tip, rough to the touch",
              "yellow catkins in February, cobnuts in clusters in autumn, multi-stemmed shrub",
              "Coppiced for centuries. The nuts are a favourite of squirrels and dormice."),
    "Hawthorn": ("small, lobed with three to five deep lobes, glossy, toothed",
                 "thorny twigs, white blossom in May, red haws berries in autumn, a hedge tree",
                 "Also called may. Haws feed thrushes and fieldfares in winter."),
    "Blackthorn": ("small oval, toothed, dull dark green, thorny",
                   "white blossom in March before the leaves, black thorny twigs, blue-black sloes in autumn",
                   "The first blossom of spring in the hedge. Sloes make sloe gin after the first frost."),
    "Elder": ("compound with five to seven oval, toothed leaflets, smelly when crushed, opposite",
              "flat creamy flower heads in June, purple-black berries in autumn, soft pithy twigs",
              "Elderflower cordial and elderberry syrup; the berries must be cooked and the rest of the plant is not for eating."),
    "Holly": ("spiny, glossy, dark evergreen, wavy edges with prickles",
              "bright red berries on female trees, smooth grey bark",
              "Evergreen and used at Christmas. The berries are poisonous to people."),
    "Rowan": ("compound with 11 to 15 leaflets in pairs, narrow, toothed, feathery",
              "clusters of bright red berries in late summer, silver-grey smooth bark, also called mountain ash",
              "Traditionally planted to ward off evil. Blackbirds and redwings strip the berries."),
    "Small-leaved lime": ("small, heart-shaped, asymmetrical, dark green, toothed edges",
                          "flowers in July that smell sweet, hairy leaf underside tufts, small round seed clusters",
                          "Bees adore the flowers; the tea is called tilleul."),
    "Hornbeam": ("oval, pointed, pleated with deep parallel veins, double-toothed, like beech but more toothed",
                 "twisted, fluted trunk, papery winged seed clusters, hedge tree",
                 "Very hard wood, once used for butchers' blocks and cogs."),
    "Willow": ("long, narrow, pointed, silvery underneath, slender",
               "grows by water, fluffy catkins in spring, wands that droop or grow straight",
               "Fast growing and used for cricket bats and baskets; aspirin was first found in the bark."),
    "Elm": ("oval with a lopsided base, rough on top, double-toothed edge, dark green",
            "small clusters of round seeds, suckers around the base, few large elms left after Dutch elm disease",
            "Wych elm still survives in the north and west."),
    "Scots pine": ("needles, long, blue-green, in pairs, twisted",
                   "orange-red flaking bark on the upper trunk, woody cones, evergreen",
                   "Britain's only native pine, home to red squirrels and capercaillie in Scotland."),
    "Yew": ("flat dark green needles in two rows, soft, evergreen",
            "red fleshy berry-like cups, reddish flaking bark, often in churchyards",
            "Very long-lived, some are over 2,000 years old. Every part except the red flesh is highly poisonous."),
}

MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October",
          "November", "December"]

# month: things to spot in the UK
SPOT = {
    1: ["Starling murmurations at dusk", "Redwings and fieldfares on berry bushes", "Snowdrops opening", "Barn owls hunting in daylight",
        "Grey seal pups on the east coast", "Garden birdwatch weekend (RSPB, last weekend of January)"],
    2: ["Frogspawn in ponds", "Hazel catkins", "Woodpeckers drumming", "Crocus and early daffodils", "Song thrush and robin song at dawn"],
    3: ["Brimstone butterflies", "Toads crossing roads on damp nights", "Blackthorn blossom", "First chiffchaff singing",
        "Hares boxing in fields", "Wild garlic leaves appearing"],
    4: ["Swallows and house martins arriving", "Cuckoo calls (rarer now)", "Bluebell woods starting", "Orange-tip butterflies",
        "Dawn chorus building", "Lambs in fields"],
    5: ["Bluebells at their best", "Swifts arriving", "Hawthorn blossom", "Dawn chorus at its peak", "Baby birds fledging",
        "Cow parsley on verges"],
    6: ["Longest days and midsummer glow-worms", "Foxgloves and poppies", "Bats over the garden at dusk", "Butterflies and bumblebees",
        "Young hedgehogs", "Seabird colonies on cliffs and puffins"],
    7: ["Butterflies, big Butterfly Count in July", "Swifts screaming over roofs", "Wildflower meadows", "Heather starting to bloom",
        "Dragonflies over ponds", "Young owls and fledged garden birds"],
    8: ["Perseid meteors", "Purple heather moors", "Migrating waders on estuaries", "Swallows gathering on wires",
        "Dragonflies and damselflies", "Grey seals on the coast"],
    9: ["Swallows and swifts leaving", "Spiders' webs in dew", "Red deer rut starting in Scotland", "Berries and fungi", "Salmon leaping in rivers",
        "Harvest moon"],
    10: ["Red deer rutting", "Autumn colours", "Geese arriving from the Arctic", "Fungi in woods", "Hedgehogs preparing to hibernate",
         "Fieldfares and redwings arriving"],
    11: ["Starling murmurations begin", "Grey seal pups born on the coast", "Bare trees showing nests", "Geese and swans arriving",
         "Fireworks night hedgehogs (check bonfires)", "Robins singing in the dark"],
    12: ["Robins singing", "Holly berries and mistletoe", "Winter thrushes in gardens", "Barn owls at dusk", "Geminid meteors",
         "Waxwings in some winters"],
}

# name: (months available, what to look for, careful notes)
FORAGE = {
    "Wild garlic (ramsons)": ([3, 4, 5], "broad leaves with a strong garlic smell, damp woods, white star flowers",
                              "Crush a leaf: it must smell of garlic. Lords-and-ladies and lily of the valley look similar and are poisonous."),
    "Nettle tops": ([3, 4, 5, 6], "the top four leaves of young plants, in soup or tea",
                     "Wear gloves; cooking removes the sting. Avoid plants near roads or dog walks."),
    "Elderflower": ([5, 6], "flat creamy flower heads with a sweet scent, for cordial",
                    "Take some from each tree and leave the rest for berries. Not to be confused with hemlock or giant hogweed."),
    "Dandelion leaves": ([3, 4, 5, 9, 10], "young leaves are best in salads; flowers make tea",
                         "Pick well away from roads and dogs, and wash well."),
    "Wild strawberries": ([6, 7], "tiny sweet berries on low plants in grassy banks",
                          "Very small, so it takes a while. Check they are not the inedible mock strawberry, which has yellow flowers."),
    "Bilberries": ([7, 8], "tiny blue-black berries on heathland and moors, stain fingers purple", "Picking takes time; they grow low."),
    "Samphire (marsh samphire)": ([7, 8], "crisp green salty stems on saltmarshes", "Check local rules; do not uproot it. Muddy and tidal ground can be dangerous."),
    "Blackberries": ([8, 9, 10], "the classic ripe black fruit from brambles",
                     "Pick above dog height and away from roads. Traditional lore says not to eat them after Michaelmas, 29 September."),
    "Elderberries": ([8, 9], "dark purple berry clusters, must be cooked", "Raw berries can make you ill, so cook them into syrup or jam."),
    "Damsons and wild plums": ([8, 9], "small purple plums in hedgerows", "Check the fruit is ripe and soft."),
    "Hazelnuts": ([9, 10], "nuts in frilly green husks; squirrels get there first", "Pick when the husk is turning brown."),
    "Crab apples": ([9, 10], "tiny sour apples for jelly", "Cook them; they are very sharp."),
    "Rosehips": ([9, 10, 11], "orange-red hips for syrup", "Strain well to remove the itchy hairs inside."),
    "Sloes": ([9, 10, 11], "blue-black berries on blackthorn, for sloe gin", "Very sour raw; sloes are best after the first frost and always cooked or steeped."),
    "Sweet chestnuts": ([10, 11], "nuts inside a spiky green case, roast them", "Not horse chestnuts (conkers) which are poisonous to eat; sweet chestnut cases are much spikier."),
    "Wild mushrooms (only with an expert)": ([9, 10], "Take an expert or a good local group", "Never eat a mushroom you cannot identify with certainty: some are deadly."),
}

FORAGING_SAFETY = [
    "Never eat anything unless you are 100 percent sure what it is; if in doubt, leave it out.",
    "Deadly look-alikes are real: hemlock and hemlock water-dropwort look like cow parsley and wild carrot, and lords-and-ladies can be mistaken for wild garlic.",
    "Use a good field guide or an expert; a phone app alone is not enough.",
    "Take only a little for yourself (about a carrier bag), leave plenty for wildlife and never uproot a plant. That is against the law on private land.",
    "Ask permission on private land; nature reserves and SSSIs often ban picking.",
    "Avoid busy road verges, dog-walking spots and sprayed fields; pick above dog height and wash everything.",
    "Try a tiny amount first, in case of an allergy, and always cook what needs cooking.",
    "Never eat wild mushrooms without an expert to confirm each one. Some deadly ones look very ordinary.",
]
