"""Reference tables for the tech helper: keyboard shortcuts by app, a jargon glossary and a cable and charger guide."""

SHORTCUTS = {
    "windows": ("Windows 11", [
        ("Win + D", "Show or hide the desktop"), ("Win + E", "Open File Explorer"),
        ("Win + L", "Lock the PC"), ("Win + I", "Open Settings"), ("Win + V", "Clipboard history"),
        ("Win + Shift + S", "Screenshot of part of the screen"), ("Win + Tab", "See all open windows and desktops"),
        ("Win + Left / Right", "Snap a window to one side"), ("Win + Ctrl + D", "New virtual desktop"),
        ("Win + .", "Emoji picker"), ("Alt + Tab", "Switch between apps"), ("Ctrl + Shift + Esc", "Task Manager"),
        ("Win + A", "Quick settings"), ("Win + X", "Power user menu"),
    ]),
    "explorer": ("File Explorer", [
        ("Ctrl + N", "New window"), ("Ctrl + Shift + N", "New folder"), ("F2", "Rename the selected file"),
        ("Alt + Up", "Go up a folder"), ("Alt + Left", "Go back"), ("Ctrl + E", "Jump to the search box"),
        ("Alt + Enter", "Properties of the selected file"), ("Shift + Delete", "Delete for good, skipping the Recycle Bin"),
        ("Ctrl + A", "Select everything"), ("F5", "Refresh"),
    ]),
    "browser": ("Chrome and Edge", [
        ("Ctrl + T", "New tab"), ("Ctrl + W", "Close the tab"), ("Ctrl + Shift + T", "Reopen the tab you just closed"),
        ("Ctrl + L", "Jump to the address bar"), ("Ctrl + Tab", "Next tab"), ("Ctrl + F", "Find on the page"),
        ("Ctrl + D", "Bookmark the page"), ("Ctrl + Shift + N", "Private window"), ("Ctrl + +/-", "Zoom in or out"),
        ("Ctrl + R", "Reload"), ("Ctrl + H", "History"), ("Ctrl + J", "Downloads"),
    ]),
    "word": ("Word", [
        ("Ctrl + B / I / U", "Bold, italic, underline"), ("Ctrl + Z / Y", "Undo, redo"), ("Ctrl + S", "Save"),
        ("Ctrl + F", "Find"), ("Ctrl + H", "Find and replace"), ("Ctrl + Enter", "New page"),
        ("Ctrl + Home / End", "Top or bottom of the document"), ("Ctrl + Left / Right", "Move a word at a time"),
        ("Ctrl + K", "Add a link"), ("F7", "Check spelling"), ("Ctrl + Alt + 1 / 2", "Heading 1 / 2"),
    ]),
    "excel": ("Excel", [
        ("Ctrl + Arrow", "Jump to the edge of the data"), ("Ctrl + ;", "Insert today's date"), ("F2", "Edit the cell"),
        ("F4", "Repeat the last action, or fix a cell reference with $"), ("Ctrl + Shift + L", "Turn filters on or off"),
        ("Alt + =", "AutoSum"), ("Ctrl + 1", "Format cells"), ("Ctrl + Space", "Select the column"),
        ("Shift + Space", "Select the row"), ("Ctrl + T", "Turn the range into a table"),
    ]),
    "text": ("Any app (editing)", [
        ("Ctrl + C", "Copy"), ("Ctrl + X", "Cut"), ("Ctrl + V", "Paste"), ("Ctrl + Shift + V", "Paste without formatting"),
        ("Ctrl + Z", "Undo"), ("Ctrl + A", "Select all"), ("Ctrl + S", "Save"), ("Ctrl + P", "Print"),
        ("Ctrl + Shift + Left / Right", "Select word by word"), ("Home / End", "Start or end of the line"),
    ]),
    "powerpoint": ("PowerPoint", [
        ("F5", "Start the slideshow from the beginning"), ("Shift + F5", "Start from this slide"),
        ("B or W", "Black or white screen during a show"), ("Ctrl + M", "New slide"), ("Ctrl + D", "Duplicate slide"),
        ("Esc", "End the show"), ("Ctrl + G", "Group objects"),
    ]),
    "vscode": ("VS Code", [
        ("Ctrl + P", "Open a file by name"), ("Ctrl + Shift + P", "Command palette"), ("Ctrl + `", "Show the terminal"),
        ("Ctrl + /", "Comment or uncomment lines"), ("Alt + Up / Down", "Move the line"),
        ("Ctrl + D", "Select the next matching word"), ("F12", "Go to definition"), ("Ctrl + B", "Show or hide the sidebar"),
    ]),
}

SHORTCUT_WORDS = {
    "windows": ["windows", "win", "desktop", "pc", "general"], "explorer": ["explorer", "files", "folder", "file"],
    "browser": ["browser", "chrome", "edge", "web", "firefox"], "word": ["word", "document", "docs"],
    "excel": ["excel", "spreadsheet", "sheet"], "text": ["text", "editing", "copy", "paste", "any", "basic"],
    "powerpoint": ["powerpoint", "slides", "presentation"], "vscode": ["code", "vscode", "vs code", "programming"],
}

JARGON = {
    "router": "The box from your broadband provider that shares the internet around your home.",
    "modem": "The part that connects your home to the phone line or cable. Often built into the router.",
    "wi-fi": "Wireless internet inside your home. It isn't the same as the internet itself.",
    "broadband": "Your home internet connection.",
    "mbps": "Megabits per second, how fast a connection is. 100 Mbps is about 12 megabytes a second.",
    "ping": "How quickly your connection answers, in milliseconds. Lower is better, mainly for games and calls.",
    "latency": "The delay before something you do online gets a response. Another word for ping.",
    "bandwidth": "How much data your connection can carry at once, like the width of a pipe.",
    "ip address": "The number that identifies a device on a network, like a house number.",
    "dns": "The internet's phone book. It turns names like bbc.co.uk into numbers.",
    "vpn": "A private tunnel for your internet traffic. It hides where you're connecting from, but it isn't a shield against viruses.",
    "cloud": "Storage and services on someone else's computers, reached over the internet, such as iCloud or OneDrive.",
    "ram": "Short-term memory. It holds what's open right now. More RAM lets you keep more open at once.",
    "ssd": "A fast drive with no moving parts. It makes a PC start and open things much faster than an old hard disk.",
    "hdd": "An older, cheaper, slower hard disk drive with spinning parts inside.",
    "cpu": "The processor, the PC's brain that does the calculating.",
    "gpu": "The graphics card or chip. It draws the picture, and matters for games and video editing.",
    "firmware": "The small built-in software inside a gadget such as a router or printer. It sometimes needs updating.",
    "driver": "A small program that lets Windows talk to a device such as a printer or graphics card.",
    "bios": "The tiny program that starts up a PC before Windows loads. Also called UEFI.",
    "cache": "A store of recent things kept close so they load faster. Clearing it can fix odd website behaviour.",
    "cookie": "A small note a website saves in your browser to remember you, for example that you're logged in.",
    "browser": "The app you use to view websites, such as Edge, Chrome, Firefox or Safari.",
    "malware": "Harmful software: viruses, spyware, ransomware and the like.",
    "ransomware": "Malware that locks your files and demands payment. Good backups are the best defence.",
    "phishing": "Fake emails or texts that trick you into giving away passwords or money.",
    "two-factor": "Using a second proof, such as a code on your phone, as well as your password. Also called 2FA or MFA.",
    "2fa": "Two-factor authentication: a password plus a code or prompt from your phone.",
    "encryption": "Scrambling data so only someone with the key can read it.",
    "firewall": "A gatekeeper that blocks unwanted connections to your PC or network.",
    "antivirus": "Software that looks for and removes malware. Windows Security does this for free.",
    "bluetooth": "Short-range wireless for headphones, speakers and keyboards.",
    "nfc": "Very short range wireless used for tapping to pay with your phone.",
    "usb-c": "The small, reversible oval plug used by modern phones, laptops and chargers.",
    "hdmi": "The cable that carries picture and sound from a PC or console to a TV or monitor.",
    "resolution": "How many dots make up the picture, for example 1920 by 1080. More dots means sharper.",
    "refresh rate": "How many times a second the screen redraws, in Hz. 60 is normal, 120 or 144 is smoother.",
    "ppi": "Pixels per inch, how sharp a screen is. Around 300 looks crisp at phone distance.",
    "4k": "A screen with about 3840 by 2160 dots, four times as many as Full HD.",
    "hdr": "High dynamic range: a wider spread of bright and dark on screen.",
    "oled": "A screen where every dot makes its own light, giving true blacks.",
    "megapixel": "A million dots in a photo. More megapixels aren't always better photos.",
    "gigabyte": "About a thousand megabytes. A phone photo is a few megabytes, an hour of HD video a few gigabytes.",
    "terabyte": "About a thousand gigabytes.",
    "bit": "The smallest piece of data, a 0 or 1. Eight bits make a byte.",
    "byte": "Eight bits, roughly one letter. Files are measured in bytes.",
    "operating system": "The main software on a device that everything else runs on, such as Windows or iOS.",
    "app": "A program on your phone or PC.",
    "widget": "A small live panel showing information, such as the weather, on your screen.",
    "beta": "An early test version of software that may still have bugs.",
    "patch": "A small update that fixes a problem.",
    "reboot": "Restart. Turning it off and on again.",
    "hotspot": "Sharing your phone's mobile data as a Wi-Fi network for other devices.",
    "airdrop": "Apple's way of sending photos and files between nearby Apple devices.",
    "icloud": "Apple's cloud service for photos, backups and files.",
    "onedrive": "Microsoft's cloud storage that comes with Windows.",
    "sim": "The small chip that connects your phone to a mobile network. An eSIM is one built into the phone.",
    "5g": "The fifth generation of mobile data. Faster than 4G where the signal is good.",
    "mesh wi-fi": "Several small units that work together to spread Wi-Fi around a big house.",
    "ethernet": "A wired network cable, usually faster and steadier than Wi-Fi.",
    "port": "A socket on a device where you plug something in.",
    "dongle": "A small adapter that plugs into a port to add a feature.",
    "screenshot": "A picture of what's on your screen. On Windows, press Win + Shift + S.",
    "pixel": "One tiny dot on a screen. A picture is made of millions of them.",
    "spam": "Unwanted junk messages.",
    "captcha": "A puzzle that checks you're a person, not a robot.",
    "password manager": "An app that creates and remembers strong passwords for you.",
    "biometrics": "Using your face or fingerprint to unlock something.",
}

CABLES = [
    (["iphone 15", "iphone 16", "iphone 17", "newer iphone", "iphone charger"],
     "iPhone 15 and newer", "USB-C to USB-C", "Any decent USB-C cable. For fast charging use a 20W or stronger USB-C charger."),
    (["iphone 14", "iphone 13", "iphone 12", "iphone 11", "older iphone", "lightning", "airpods"],
     "iPhone 14 and older, AirPods cases", "Lightning to USB-C", "Use a 20W USB-C charger for fast charging. Old USB-A chargers work but slowly."),
    (["android", "samsung", "pixel", "phone charger"],
     "Most Android phones", "USB-C to USB-C", "Check the phone's wattage; a 25W to 45W USB-C charger suits most."),
    (["laptop", "macbook", "laptop charger"],
     "Laptops", "The laptop's own charger, or USB-C Power Delivery", "Match the watts: 65W for most thin laptops, 100W or more for big ones. A weaker charger charges slowly or not at all."),
    (["ipad", "tablet"],
     "iPad and tablets", "USB-C to USB-C (Lightning on old iPads)", "A 20W to 30W charger is fine."),
    (["monitor", "second screen", "screen", "display", "4k", "144hz"],
     "Monitors", "DisplayPort or HDMI 2.0 and above", "For 4K at 60Hz or 1440p at 144Hz use DisplayPort or an HDMI 2.1 cable. An old HDMI cable may limit the picture."),
    (["tv", "television", "console", "ps5", "xbox", "hdmi"],
     "TVs and consoles", "HDMI", "Look for HDMI 2.1 on the label for 4K at 120Hz. Any Premium High Speed cable will do for 4K at 60Hz."),
    (["headphones", "earbuds", "aux", "speaker"],
     "Headphones and speakers", "3.5mm audio jack, or Bluetooth", "Some phones have no headphone jack; a USB-C or Lightning adapter adds one."),
    (["router", "ethernet", "wired", "cat6", "network cable", "internet cable"],
     "Wired internet", "Ethernet, Cat 5e or Cat 6", "Cat 6 handles gigabit easily. Keep runs under 100 metres."),
    (["camera", "gopro", "kindle", "e-reader", "micro usb", "old phone"],
     "Cameras, e-readers and older gadgets", "Micro-USB or USB-C; check the socket", "Look closely at the socket: micro-USB is a thin trapezoid, USB-C is a small oval."),
    (["smartwatch", "apple watch", "watch", "fitbit"],
     "Smartwatches", "The watch's own dock or charger", "These use special magnetic chargers. Buy the same brand or a well-reviewed copy."),
    (["power bank", "battery pack", "portable charger"],
     "Power banks", "USB-C in and out", "For a laptop pick a bank with 65W output. Check it says Power Delivery or PD."),
]

CONNECTORS = [
    ("USB-C", "Small oval, plugs in either way up", "Newer phones, laptops, tablets"),
    ("Lightning", "Small flat, either way up (Apple)", "iPhone 14 and older, AirPods cases"),
    ("USB-A", "Big rectangle, one way up", "Older chargers, PCs, memory sticks"),
    ("Micro-USB", "Small trapezoid, one way up", "Older Android phones, some gadgets"),
    ("HDMI", "Wide flat trapezoid", "TVs, monitors, consoles"),
    ("DisplayPort", "Like HDMI with one cut corner", "PC monitors"),
    ("3.5mm jack", "Round audio plug", "Wired headphones, speakers"),
    ("Ethernet", "Chunky clip-in plug", "Wired internet"),
]
