"""Travel reference tables kept on this PC: plugs, voltage, driving side, emergency numbers and tipping for about
70 countries, a 20-phrase phrasebook in 10 languages, and the built-in travel checklists.

Figures are the usual ones as of 2026; they're a guide, so check anything important before you go.
"""

# name: (plug types, voltage, frequency Hz, driving side, emergency number(s), tipping)
COUNTRIES = {
    "United Kingdom": ("G", "230", 50, "left", "999 or 112", "10 to 12.5% in restaurants if service isn't added"),
    "Ireland": ("G", "230", 50, "left", "112 or 999", "10 to 15% in restaurants"),
    "France": ("C, E", "230", 50, "right", "112", "service is included; round up or leave a euro or two"),
    "Spain": ("C, F", "230", 50, "right", "112", "not expected; round up or 5 to 10% for good service"),
    "Portugal": ("C, F", "230", 50, "right", "112", "5 to 10% in restaurants"),
    "Italy": ("C, F, L", "230", 50, "right", "112", "a cover charge (coperto) is common; round up if you like"),
    "Germany": ("C, F", "230", 50, "right", "112", "round up or 5 to 10%, handed over, not left on the table"),
    "Netherlands": ("C, F", "230", 50, "right", "112", "round up or 5 to 10%"),
    "Belgium": ("C, E", "230", 50, "right", "112", "service is included; round up"),
    "Luxembourg": ("C, F", "230", 50, "right", "112", "service is included; round up"),
    "Switzerland": ("C, J", "230", 50, "right", "112 (ambulance 144)", "service is included; round up"),
    "Austria": ("C, F", "230", 50, "right", "112", "5 to 10%"),
    "Denmark": ("C, E, F, K", "230", 50, "right", "112", "service is included; round up"),
    "Sweden": ("C, F", "230", 50, "right", "112", "service is included; round up"),
    "Norway": ("C, F", "230", 50, "right", "112 (ambulance 113)", "service is included; round up"),
    "Finland": ("C, F", "230", 50, "right", "112", "not expected"),
    "Iceland": ("C, F", "230", 50, "right", "112", "not expected"),
    "Greece": ("C, F", "230", 50, "right", "112", "5 to 10%"),
    "Cyprus": ("G", "230", 50, "left", "112 or 199", "about 10%"),
    "Malta": ("G", "230", 50, "left", "112", "5 to 10%"),
    "Croatia": ("C, F", "230", 50, "right", "112", "about 10%"),
    "Slovenia": ("C, F", "230", 50, "right", "112", "round up or about 10%"),
    "Poland": ("C, E", "230", 50, "right", "112", "about 10%"),
    "Czech Republic": ("C, E", "230", 50, "right", "112", "about 10%"),
    "Hungary": ("C, F", "230", 50, "right", "112", "10 to 15%; check for a service charge first"),
    "Romania": ("C, F", "230", 50, "right", "112", "about 10%"),
    "Bulgaria": ("C, F", "230", 50, "right", "112", "about 10%"),
    "Turkey": ("C, F", "230", 50, "right", "112", "5 to 10%"),
    "Estonia": ("C, F", "230", 50, "right", "112", "not expected; round up"),
    "Latvia": ("C, F", "230", 50, "right", "112", "about 10%"),
    "Lithuania": ("C, F", "230", 50, "right", "112", "about 10%"),
    "United States": ("A, B", "120", 60, "right", "911", "15 to 20% in restaurants, bars and taxis"),
    "Canada": ("A, B", "120", 60, "right", "911", "15 to 20% in restaurants, bars and taxis"),
    "Mexico": ("A, B", "127", 60, "right", "911", "10 to 15%"),
    "Costa Rica": ("A, B", "120", 60, "right", "911", "10% service is added by law; extra is optional"),
    "Cuba": ("A, B, C, L", "110 or 220", 60, "right", "106 police, 104 ambulance", "about 10%, cash"),
    "Jamaica": ("A, B", "110", 50, "left", "119 police, 110 ambulance and fire", "10 to 15%"),
    "Barbados": ("A, B", "115", 50, "left", "211 police, 511 ambulance", "10 to 15% if service isn't added"),
    "Dominican Republic": ("A, B", "120", 60, "right", "911", "10% is added; about 10% more for good service"),
    "Brazil": ("C, N", "127 or 220", 60, "right", "190 police, 192 ambulance", "10% is usually added"),
    "Argentina": ("C, I", "220", 50, "right", "911", "about 10%"),
    "Chile": ("C, L", "220", 50, "right", "133 police, 131 ambulance", "about 10%"),
    "Peru": ("A, C", "220", 60, "right", "105 police, 106 ambulance", "about 10%"),
    "Colombia": ("A, B", "110", 60, "right", "123", "10% is often suggested on the bill"),
    "South Africa": ("C, D, M, N", "230", 50, "left", "10111 police, 10177 ambulance, 112 from a mobile",
                     "10 to 15%; tip car guards and petrol attendants a few rand"),
    "Namibia": ("D, M", "220", 50, "left", "10111 police", "about 10%"),
    "Botswana": ("D, G", "230", 50, "left", "999 police, 997 ambulance", "about 10%"),
    "Zimbabwe": ("D, G", "220", 50, "left", "999, 995 police, 994 ambulance", "about 10%"),
    "Kenya": ("G", "240", 50, "left", "999 or 112", "about 10%"),
    "Tanzania": ("D, G", "230", 50, "left", "112", "about 10%"),
    "Mauritius": ("C, G", "230", 50, "left", "999 or 112", "about 10%"),
    "Seychelles": ("G", "240", 50, "left", "999", "service is often added"),
    "Nigeria": ("D, G", "230", 50, "right", "112", "about 10%"),
    "Ghana": ("D, G", "230", 50, "right", "112", "about 10%"),
    "Morocco": ("C, E", "220", 50, "right", "19 police, 15 ambulance", "about 10%, and small tips for help"),
    "Tunisia": ("C, E", "230", 50, "right", "197 police, 190 ambulance", "about 10%"),
    "Egypt": ("C, F", "220", 50, "right", "122 police, 123 ambulance", "10 to 15%, plus small tips (baksheesh)"),
    "United Arab Emirates": ("C, D, G", "230", 50, "right", "999 police, 998 ambulance",
                             "10 to 15% if service isn't added"),
    "Qatar": ("D, G", "240", 50, "right", "999", "about 10%"),
    "Saudi Arabia": ("A, B, G", "230", 60, "right", "911", "about 10%"),
    "Jordan": ("C, D, F, G, J", "230", 50, "right", "911", "about 10%"),
    "Israel": ("C, H", "230", 50, "right", "100 police, 101 ambulance", "12 to 15%"),
    "India": ("C, D, M", "230", 50, "left", "112", "about 10%"),
    "Sri Lanka": ("D, G, M", "230", 50, "left", "119 police, 1990 ambulance", "about 10% if service isn't added"),
    "Maldives": ("C, D, G, J, K, L", "230", 50, "left", "119 police, 102 ambulance", "10% service is added"),
    "Nepal": ("C, D, M", "230", 50, "left", "100 police, 102 ambulance", "about 10%"),
    "Thailand": ("A, B, C, O", "230", 50, "left", "191 police, 1669 ambulance, 1155 tourist police",
                 "round up or about 10%"),
    "Vietnam": ("A, C, D", "220", 50, "right", "113 police, 115 ambulance", "not expected but welcome"),
    "Cambodia": ("A, C, G", "230", 50, "right", "117 police, 119 ambulance", "small tips are welcome"),
    "Malaysia": ("G", "240", 50, "left", "999", "not expected; service is often added"),
    "Singapore": ("G", "230", 50, "left", "999 police, 995 ambulance", "not expected; service is usually added"),
    "Indonesia": ("C, F", "230", 50, "left", "112", "5 to 10% if service isn't added"),
    "Philippines": ("A, B, C", "220", 60, "right", "911", "about 10%"),
    "China": ("A, C, I", "220", 50, "right", "110 police, 120 ambulance", "not expected"),
    "Hong Kong": ("G", "220", 50, "left", "999", "10% service is usually added"),
    "Taiwan": ("A, B", "110", 60, "right", "110 police, 119 ambulance", "not expected"),
    "Japan": ("A, B", "100", 50, "left", "110 police, 119 ambulance", "not done; it can cause confusion"),
    "South Korea": ("C, F", "220", 60, "right", "112 police, 119 ambulance", "not expected"),
    "Australia": ("I", "230", 50, "left", "000 (112 from a mobile)", "not expected; 10% for great service"),
    "New Zealand": ("I", "230", 50, "left", "111", "not expected"),
    "Fiji": ("I", "240", 50, "left", "911", "not expected"),
}

ALIASES = {
    "uk": "United Kingdom", "britain": "United Kingdom", "great britain": "United Kingdom", "england": "United Kingdom",
    "scotland": "United Kingdom", "wales": "United Kingdom", "northern ireland": "United Kingdom",
    "usa": "United States", "us": "United States", "america": "United States", "united states of america": "United States",
    "holland": "Netherlands", "the netherlands": "Netherlands", "czechia": "Czech Republic", "turkiye": "Turkey",
    "türkiye": "Turkey", "uae": "United Arab Emirates", "dubai": "United Arab Emirates", "abu dhabi": "United Arab Emirates",
    "bali": "Indonesia", "korea": "South Korea", "sa": "South Africa", "rsa": "South Africa", "mzansi": "South Africa",
    "tenerife": "Spain", "majorca": "Spain", "mallorca": "Spain", "ibiza": "Spain", "canary islands": "Spain",
    "madeira": "Portugal", "crete": "Greece", "corfu": "Greece", "sicily": "Italy", "sardinia": "Italy",
    "hawaii": "United States", "zanzibar": "Tanzania",
}

# English, then each language's phrase; the tuple is (phrase, how to say it) where the script isn't Latin.
LANGUAGES = {
    "French": "fr-FR", "Spanish": "es-ES", "Italian": "it-IT", "German": "de-DE", "Portuguese": "pt-PT",
    "Dutch": "nl-NL", "Greek": "el-GR", "Turkish": "tr-TR", "Japanese": "ja-JP", "Mandarin": "zh-CN",
}
LANGUAGE_ALIASES = {"chinese": "Mandarin", "portugal": "Portuguese", "brazilian": "Portuguese", "france": "French",
                    "spain": "Spanish", "italy": "Italian", "germany": "German", "netherlands": "Dutch",
                    "holland": "Dutch", "greece": "Greek", "turkey": "Turkish", "japan": "Japanese", "china": "Mandarin",
                    "austria": "German", "switzerland": "German", "mexico": "Spanish", "belgium": "French",
                    "cyprus": "Greek", "flemish": "Dutch"}

PHRASES = [
    ("Hello", {"French": "Bonjour", "Spanish": "Hola", "Italian": "Buongiorno", "German": "Hallo",
               "Portuguese": "Olá", "Dutch": "Hallo", "Greek": ("Γεια σας", "Yia sas"), "Turkish": "Merhaba",
               "Japanese": ("こんにちは", "Konnichiwa"), "Mandarin": ("你好", "Nǐ hǎo")}),
    ("Goodbye", {"French": "Au revoir", "Spanish": "Adiós", "Italian": "Arrivederci", "German": "Auf Wiedersehen",
                 "Portuguese": "Adeus", "Dutch": "Tot ziens", "Greek": ("Αντίο", "Andío"), "Turkish": "Hoşça kalın",
                 "Japanese": ("さようなら", "Sayōnara"), "Mandarin": ("再见", "Zàijiàn")}),
    ("Please", {"French": "S'il vous plaît", "Spanish": "Por favor", "Italian": "Per favore", "German": "Bitte",
                "Portuguese": "Por favor", "Dutch": "Alstublieft", "Greek": ("Παρακαλώ", "Parakaló"),
                "Turkish": "Lütfen", "Japanese": ("お願いします", "Onegaishimasu"), "Mandarin": ("请", "Qǐng")}),
    ("Thank you", {"French": "Merci", "Spanish": "Gracias", "Italian": "Grazie", "German": "Danke",
                   "Portuguese": "Obrigado (a woman says Obrigada)", "Dutch": "Dank u wel",
                   "Greek": ("Ευχαριστώ", "Efcharistó"), "Turkish": "Teşekkür ederim",
                   "Japanese": ("ありがとうございます", "Arigatō gozaimasu"), "Mandarin": ("谢谢", "Xièxie")}),
    ("Yes", {"French": "Oui", "Spanish": "Sí", "Italian": "Sì", "German": "Ja", "Portuguese": "Sim", "Dutch": "Ja",
             "Greek": ("Ναι", "Ne"), "Turkish": "Evet", "Japanese": ("はい", "Hai"), "Mandarin": ("是的", "Shì de")}),
    ("No", {"French": "Non", "Spanish": "No", "Italian": "No", "German": "Nein", "Portuguese": "Não", "Dutch": "Nee",
            "Greek": ("Όχι", "Óchi"), "Turkish": "Hayır", "Japanese": ("いいえ", "Iie"),
            "Mandarin": ("不是", "Bú shì")}),
    ("Excuse me", {"French": "Excusez-moi", "Spanish": "Disculpe", "Italian": "Mi scusi", "German": "Entschuldigung",
                   "Portuguese": "Com licença", "Dutch": "Pardon", "Greek": ("Με συγχωρείτε", "Me sinchoríte"),
                   "Turkish": "Affedersiniz", "Japanese": ("すみません", "Sumimasen"),
                   "Mandarin": ("打扰一下", "Dǎrǎo yíxià")}),
    ("Sorry", {"French": "Désolé", "Spanish": "Lo siento", "Italian": "Mi dispiace", "German": "Es tut mir leid",
               "Portuguese": "Desculpe", "Dutch": "Sorry", "Greek": ("Συγγνώμη", "Signómi"),
               "Turkish": "Özür dilerim", "Japanese": ("ごめんなさい", "Gomen nasai"),
               "Mandarin": ("对不起", "Duìbuqǐ")}),
    ("Do you speak English?", {
        "French": "Parlez-vous anglais ?", "Spanish": "¿Habla inglés?", "Italian": "Parla inglese?",
        "German": "Sprechen Sie Englisch?", "Portuguese": "Fala inglês?", "Dutch": "Spreekt u Engels?",
        "Greek": ("Μιλάτε αγγλικά;", "Miláte angliká?"), "Turkish": "İngilizce konuşuyor musunuz?",
        "Japanese": ("英語を話せますか？", "Eigo o hanasemasu ka?"),
        "Mandarin": ("你会说英语吗？", "Nǐ huì shuō Yīngyǔ ma?")}),
    ("I don't understand", {
        "French": "Je ne comprends pas", "Spanish": "No entiendo", "Italian": "Non capisco",
        "German": "Ich verstehe nicht", "Portuguese": "Não compreendo", "Dutch": "Ik begrijp het niet",
        "Greek": ("Δεν καταλαβαίνω", "Den katalavéno"), "Turkish": "Anlamıyorum",
        "Japanese": ("わかりません", "Wakarimasen"), "Mandarin": ("我不明白", "Wǒ bù míngbai")}),
    ("How much is it?", {
        "French": "C'est combien ?", "Spanish": "¿Cuánto cuesta?", "Italian": "Quanto costa?",
        "German": "Wie viel kostet das?", "Portuguese": "Quanto custa?", "Dutch": "Hoeveel kost het?",
        "Greek": ("Πόσο κάνει;", "Póso kánei?"), "Turkish": "Bu ne kadar?",
        "Japanese": ("いくらですか？", "Ikura desu ka?"), "Mandarin": ("多少钱？", "Duōshao qián?")}),
    ("Where is the toilet?", {
        "French": "Où sont les toilettes ?", "Spanish": "¿Dónde está el baño?", "Italian": "Dov'è il bagno?",
        "German": "Wo ist die Toilette?", "Portuguese": "Onde é a casa de banho?", "Dutch": "Waar is het toilet?",
        "Greek": ("Πού είναι η τουαλέτα;", "Pou íne i toualéta?"), "Turkish": "Tuvalet nerede?",
        "Japanese": ("トイレはどこですか？", "Toire wa doko desu ka?"),
        "Mandarin": ("洗手间在哪里？", "Xǐshǒujiān zài nǎlǐ?")}),
    ("The bill, please", {
        "French": "L'addition, s'il vous plaît", "Spanish": "La cuenta, por favor", "Italian": "Il conto, per favore",
        "German": "Die Rechnung, bitte", "Portuguese": "A conta, por favor", "Dutch": "De rekening, alstublieft",
        "Greek": ("Τον λογαριασμό, παρακαλώ", "Ton logariasmó, parakaló"), "Turkish": "Hesap, lütfen",
        "Japanese": ("お会計をお願いします", "Okaikei o onegaishimasu"),
        "Mandarin": ("买单，谢谢", "Mǎidān, xièxie")}),
    ("A table for two, please", {
        "French": "Une table pour deux, s'il vous plaît", "Spanish": "Una mesa para dos, por favor",
        "Italian": "Un tavolo per due, per favore", "German": "Einen Tisch für zwei, bitte",
        "Portuguese": "Uma mesa para dois, por favor", "Dutch": "Een tafel voor twee, alstublieft",
        "Greek": ("Ένα τραπέζι για δύο, παρακαλώ", "Éna trapézi ya dío, parakaló"),
        "Turkish": "İki kişilik bir masa, lütfen", "Japanese": ("二人です", "Futari desu"),
        "Mandarin": ("两位，谢谢", "Liǎng wèi, xièxie")}),
    ("Water, please", {
        "French": "De l'eau, s'il vous plaît", "Spanish": "Agua, por favor", "Italian": "Acqua, per favore",
        "German": "Wasser, bitte", "Portuguese": "Água, por favor", "Dutch": "Water, alstublieft",
        "Greek": ("Νερό, παρακαλώ", "Neró, parakaló"), "Turkish": "Su, lütfen",
        "Japanese": ("お水をください", "Omizu o kudasai"), "Mandarin": ("请给我水", "Qǐng gěi wǒ shuǐ")}),
    ("Help!", {"French": "Au secours !", "Spanish": "¡Socorro!", "Italian": "Aiuto!", "German": "Hilfe!",
               "Portuguese": "Socorro!", "Dutch": "Help!", "Greek": ("Βοήθεια!", "Voíthia!"), "Turkish": "İmdat!",
               "Japanese": ("助けて！", "Tasukete!"), "Mandarin": ("救命！", "Jiùmìng!")}),
    ("I need a doctor", {
        "French": "J'ai besoin d'un médecin", "Spanish": "Necesito un médico", "Italian": "Ho bisogno di un medico",
        "German": "Ich brauche einen Arzt", "Portuguese": "Preciso de um médico", "Dutch": "Ik heb een dokter nodig",
        "Greek": ("Χρειάζομαι γιατρό", "Chriázome yiatró"), "Turkish": "Doktora ihtiyacım var",
        "Japanese": ("医者が必要です", "Isha ga hitsuyō desu"), "Mandarin": ("我需要医生", "Wǒ xūyào yīshēng")}),
    ("Where is the train station?", {
        "French": "Où est la gare ?", "Spanish": "¿Dónde está la estación de tren?", "Italian": "Dov'è la stazione?",
        "German": "Wo ist der Bahnhof?", "Portuguese": "Onde é a estação de comboios?", "Dutch": "Waar is het station?",
        "Greek": ("Πού είναι ο σιδηροδρομικός σταθμός;", "Pou íne o sidirodromikós stathmós?"),
        "Turkish": "Tren istasyonu nerede?", "Japanese": ("駅はどこですか？", "Eki wa doko desu ka?"),
        "Mandarin": ("火车站在哪里？", "Huǒchēzhàn zài nǎlǐ?")}),
    ("Good evening", {"French": "Bonsoir", "Spanish": "Buenas noches", "Italian": "Buonasera", "German": "Guten Abend",
                      "Portuguese": "Boa noite", "Dutch": "Goedenavond", "Greek": ("Καλησπέρα", "Kalispéra"),
                      "Turkish": "İyi akşamlar", "Japanese": ("こんばんは", "Konbanwa"),
                      "Mandarin": ("晚上好", "Wǎnshang hǎo")}),
    ("Cheers!", {"French": "Santé !", "Spanish": "¡Salud!", "Italian": "Salute!", "German": "Prost!",
                 "Portuguese": "Saúde!", "Dutch": "Proost!", "Greek": ("Γεια μας!", "Yia mas!"), "Turkish": "Şerefe!",
                 "Japanese": ("乾杯！", "Kanpai!"), "Mandarin": ("干杯！", "Gānbēi!")}),
]

CHECKLISTS = {
    "before you go": [
        "Lock all windows and doors", "Water the plants or ask a neighbour", "Put the bins out (and ask someone to bring them in)",
        "Cancel the milk and papers", "Empty the fridge of things that will go off", "Unplug chargers and the TV",
        "Turn the heating down or to holiday mode", "Set timer lights", "Tell a neighbour you're away",
        "Take the rubbish out", "Pay any bills due while you're away", "Tell the bank you're travelling",
        "Download maps, boarding passes and tickets", "Charge phone, power bank and headphones",
    ],
    "airport day": [
        "Passport", "Boarding passes", "Phone and charger", "Wallet, cards and some local cash",
        "Liquids under 100 ml in a clear bag", "Check in online", "Check the flight is on time",
        "Leave for the airport (allow 2 hours for short flights, 3 for long)", "Parking or taxi booked",
        "Travel insurance details", "Medicines in hand luggage", "Keys for home",
    ],
    "coming home": [
        "Check the room and safe", "Chargers from the walls", "Passport and tickets", "Check in for the flight home",
        "Spend or keep the last local cash", "Book the taxi or check the parking", "Something in for breakfast at home",
    ],
}
